// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=exe, toplevel=false, use-js-string=true, version=6.4.1
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:!0,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(c){"use strict";function
gZ(a,b,c,d){if(a[b+1]===c){a[b+1]=d;return 1}return 0}var
ek=4096,e="",az=1024;function
bV(a,b,c){var
d=String.fromCharCode;if(b===0&&c<=ek&&c===a.length)return d.apply(null,a);var
f=e;for(;0<c;b+=az,c-=az)f+=d.apply(null,a.subarray(b,b+Math.min(c,az)));return f}function
bK(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
ar(a,b,c,d,e){if(e===0)return 0;if(d===0&&(e>=c.l||c.t===2&&e>=c.c.length)){c.c=a.t===4?bV(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else if(c.t===2&&d===c.c.length){c.c+=a.t===4?bV(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else{if(c.t!==4)bK(c);var
g=a.c,h=c.c;if(a.t===4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}var
C=0xffff,bB=0xbf,eT=0xc0,cI=0xe0,P=0x3f,Q=0x80,cS=0xf0,cP=0xd800,cE=0x3ff,a6=0xdc00,ea=0x10000,hV={decode:a=>{var
h=a.length,l=e,b=0,f=0xfffd,i=a=>(a&eT)===Q;while(b<h){var
d=a[b++],c;if(d<Q)c=d;else{var
m=0xf4;if(d<0xc2||d>m)c=f;else if(d<cI)if(b<h&&i(a[b]))c=(d&0x1f)<<6|a[b++]&P;else
c=f;else if(d<cS){var
k=d===cI?0xa0:Q,j=d===0xed?0x9f:bB,g=b<h?a[b]:-1;if(g<k||g>j)c=f;else if(b+1<h&&i(a[b+1])){c=(d&0x0f)<<12|(g&P)<<6|a[b+1]&P;b+=2}else{c=f;b+=1}}else{var
k=d===cS?0x90:Q,j=d===m?0x8f:bB,g=b<h?a[b]:-1;if(g<k||g>j)c=f;else if(b+1<h&&i(a[b+1]))if(b+2<h&&i(a[b+2])){c=(d&0x07)<<18|(g&P)<<12|(a[b+1]&P)<<6|a[b+2]&P;b+=3}else{c=f;b+=2}else{c=f;b+=1}}}if(c<=C)l+=String.fromCharCode(c);else{c-=ea;l+=String.fromCharCode(cP|c>>10,a6|c&cE)}}return l}},ft=typeof
TextDecoder!=="undefined"?new
TextDecoder():hV;function
dd(a){if(a.t!==4)bK(a);return a.c}function
at(a,b){return b.repeat(a)}function
bL(a){if(a.t===2)a.c+=at(a.l-a.c.length,"\0");else
a.c=bV(a.c,0,a.c.length);a.t=0}var
cH=127;function
df(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>cH)return!1;return!0}else
return!/[^\x00-\x7f]/.test(a)}class
aA{constructor(a,b,c){this.t=a;this.c=b;this.l=c}toString(){switch(this.t){case
9:case
8:return this.c;case
4:case
2:bL(this);case
0:if(df(this.c))this.t=9;else
this.t=8;return this.c}}toUtf16(){if(this.t===9)return this.c;var
a=dd(this);return ft.decode(a)}slice(){var
a=this.t===4?this.c.slice():this.c;return new
aA(this.t,a,this.l)}}function
e6(a){return new
aA(0,a,a.length)}function
aU(a){return a}function
aB(a){return e6(aU(a))}function
bI(a,b,c,d,e){ar(aB(a),b,c,d,e);return 0}var
fs={};function
hU(a){if(Object.hasOwn(fs,a))return fs[a];var
b=c.process;if(b?.env&&Object.hasOwn(b.env,a))return b.env[a];var
d=c.std;if(d&&typeof
d.getenviron==="function"){var
e=d.getenviron()[a];if(e!==undefined)return e}if(c.jsoo_env&&typeof
c.jsoo_env[a]==="string")return c.jsoo_env[a]}var
bT=0,ei=",";(function(){var
c=hU("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(ei);for(var
a=0;a<b.length;a++)if(b[a]==="b")bT=1;else if(b[a].startsWith("b="))bT=+b[a].slice(2);else
continue}}());var
hL=bT,R=[0],u=248;function
g9(a,b){if(!a.js_error||b||a[0]===u)a.js_error=new
c.Error("Js exception containing backtrace");return a}function
j(a,b){return bT&&hL?g9(a,b):a}function
fm(a,b){throw j([0,a,b])}function
aj(a){return a}function
fo(a,b){fm(a,aj(b))}function
s(a){fo(R["predef:Invalid_argument"],a)}var
cM="index out of bounds";function
g3(){s(cM)}var
G=0xff;function
q(a,b,c){c&=G;if(a.t!==4){if(b===a.c.length){a.c+=String.fromCharCode(c);if(b+1===a.l)a.t=0;return 0}bK(a)}a.c[b]=c;return 0}function
aC(a,b,c){if(b>>>0>=a.l)g3();return q(a,b,c)}function
cY(a,b){switch(a.t&6){case
0:return a.c.charCodeAt(b);case
2:if(b>=a.c.length)return 0;return a.c.charCodeAt(b);case
4:return a.c[b]}}function
as(d,e){var
f=d.l>=0?d.l:d.l=d.length,c=e.length,b=f-c;if(b===0)return d(...e);else if(b<0){var
a=d(...e.slice(0,f));if(typeof
a!=="function")return a;return as(a,e.slice(f))}else{switch(b){case
1:{var
a=function(a){var
f=new
Array(c+1);for(var
b=0;b<c;b++)f[b]=e[b];f[c]=a;return d(...f)};break}case
2:{var
a=function(a,b){var
g=new
Array(c+2);for(var
f=0;f<c;f++)g[f]=e[f];g[c]=a;g[c+1]=b;return d(...g)};break}default:var
a=function(...a){if(a.length===0)a=[undefined];return as(d,e.concat(a))}}a.l=b;return a}}function
bH(){s(cM)}function
e8(a,b){if(b>>>0>=a.length-1)bH();return a}function
g6(a){if(Number.isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!==0)return 1;return 2}return Number.isNaN(a)?4:3}function
g7(){return[0]}function
z(a){if(a<0)s("Bytes.create");return new
aA(a?2:9,e,a)}function
hu(a){return a===245?1:0}var
cJ=0x7c00,cR=0x80000000,cF=0x7f800000,fc=function(){const
a=new
ArrayBuffer(4),d=new
Float32Array(a),e=new
Uint32Array(a);return function(a){d[0]=a;let
b=e[0]>>>0;const
f=b&cR;b=(b^f)>>>0;let
c;if(b>=0x47800000)c=b>cF?0x7e00:cJ;else if(b<0x38800000){e[0]=b;d[0]=d[0]+.5;c=e[0]-0x3f000000>>>0}else
c=b+0xc8000fff+(b>>>13&1)>>>13;return(c|f>>>16)&C}}(),$=new
DataView(new
ArrayBuffer(8));function
bO(a){$.setFloat32(0,a,!0);return $.getUint32(0,!0)|0}var
bc=Math.pow(2,-24);function
hK(a){throw a}function
fp(){hK(R["predef:Division_by_zero"])}var
ao=0x8000,y=0xffffff,a=0x000000;class
d{constructor(a,b,c){this.lo=a&y;this.mi=b&y;this.hi=c&C;this.caml_custom="_j"}static
UNSIGNED_MAX=new
d(y,y,C);static
SIGNED_MAX=new
d(y,y,0x7fff);static
SIGNED_MIN=new
d(a,a,ao);slice(){return new
d(this.lo,this.mi,this.hi)}ucompare(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}compare(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0}neg(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
d(a,b,c)}add(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),e=this.hi+a.hi+(c>>24);return new
d(b,c,e)}sub(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),e=this.hi-a.hi+(c>>24);return new
d(b,c,e)}mul(a){var
b=this.lo*a.lo,c=(b*bc|0)+this.mi*a.lo+this.lo*a.mi,e=(c*bc|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
d(b,c,e)}isZero(){return(this.lo|this.mi|this.hi)===0}isNeg(){return this.hi<<16<0}and(a){return new
d(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)}or(a){return new
d(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)}xor(a){return new
d(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)}shift_left(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
d(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
d(0,0,this.lo<<a-48)}shift_right_unsigned(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
d(this.hi>>a-48,0,0)}shift_right(a){a=a&63;if(a===0)return this;var
c=this.hi<<16>>16;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
d(this.mi>>a-24|c<<48-a,this.hi<<16>>a-24>>16,b&C);return new
d(this.hi<<16>>a-32,b,b)}lsl1(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&y;this.lo=this.lo<<1&y}lsr1(){this.lo=(this.lo>>>1|this.mi<<23)&y;this.mi=(this.mi>>>1|this.hi<<23)&y;this.hi=this.hi>>>1}udivmod(a){var
e=0,c=this.slice(),b=a.slice(),f=new
d(0,0,0);while(c.ucompare(b)>0){e++;b.lsl1()}while(e>=0){e--;f.lsl1();if(c.ucompare(b)>=0){f.lo++;c=c.sub(b)}b.lsr1()}return{quotient:f,modulus:c}}div(a){var
b=this;if(a.isZero())fp();var
d=b.hi^a.hi;if(b.hi&ao)b=b.neg();if(a.hi&ao)a=a.neg();var
c=b.udivmod(a).quotient;if(d&ao)c=c.neg();return c}mod(a){var
b=this;if(a.isZero())fp();var
d=b.hi;if(b.hi&ao)b=b.neg();if(a.hi&ao)a=a.neg();var
c=b.udivmod(a).modulus;if(d&ao)c=c.neg();return c}toInt(){return this.lo|this.mi<<24}toFloat(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo}toArray(){return[this.hi>>8,this.hi&G,this.mi>>16,this.mi>>8&G,this.mi&G,this.lo>>16,this.lo>>8&G,this.lo&G]}lo32(){return this.lo|(this.mi&G)<<24}hi32(){return this.mi>>>8&C|this.hi<<16}}function
hi(a,b,c){return new
d(a,b,c)}var
eC=0xf,eB=0x7ff8,eR=0x7ff0;function
bP(a){$.setFloat64(0,a,!0);var
e=$.getUint32(0,!0),c=$.getUint32(4,!0),d=e&y,f=e>>>24|c<<8&y,b=c>>>16&C;if((b&eB)===eR&&(f|d|b&eC)!==0)b|=8;return hi(d,f,b)}function
bd(a){return a.toArray()}var
bx="_bigarr02";function
e5(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom===bx)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<C)a.write(16,b.dims[d]);else{a.write(16,C);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=bd(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=bd(bP(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
13:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
0:for(var
d=0;d<b.data.length;d++){var
f=bO(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,bO(e[1]));a.write(32,bO(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=bd(bP(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=bd(bP(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}var
cZ=function(){var
h=Math.pow,e=31,i=1023,f=h(2,-24),g=.0009765625;return function(a){var
d=a>>>15,c=a>>>10&e,b=a&i;if(c===e)return b===0?d===0?Number.POSITIVE_INFINITY:Number.NEGATIVE_INFINITY:Number.NaN;if(c===0)return b*(d===0?f:-f);var
j=h(2,c-15)*(d===0?1+b*g:-1-b*g);return j}}();function
e3(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
g0(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break;case
13:c=Uint16Array;break}if(!c)s("Bigarray.create: unsupported kind");var
d=new
c(b*e3(a));return d}function
c3(a){$.setUint32(0,a,!0);return $.getFloat32(0,!0)}function
bb(a){return new
d(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
c4(a){var
d=a.lo,c=a.mi,b=a.hi;if((b&eB)===eR&&(c|d|b&eC)!==0)b|=8;$.setUint32(0,d|c<<24,!0);$.setUint32(4,c>>>8|b<<16,!0);return $.getFloat64(0,!0)}function
cX(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)s("Bigarray.create: negative dimension");c=c*a[b]}return c}function
hh(a,b){return new
d(a&y,a>>>24&G|(b&C)<<8,b>>>16&C)}function
c5(a){return a.hi32()}function
c6(a){return a.lo32()}var
g1=bx,bA=254;class
eZ{constructor(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d;this.caml_custom=g1}offset(a){var
c=0;if(typeof
a==="number")a=[a];if(!Array.isArray(a))s("bigarray.js: invalid offset");if(this.dims.length!==a.length)s("Bigarray.get/set: bad number of dimensions");if(this.layout===0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])bH();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])bH();c=c*this.dims[b]+(a[b]-1)}return c}get(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return hh(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[bA,e,c];case
13:return cZ(this.data[a]);default:return this.data[a]}}set(a,b){switch(this.kind){case
7:this.data[a*2+0]=c6(b);this.data[a*2+1]=c5(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;case
13:this.data[a]=fc(b);break;default:this.data[a]=b;break}return 0}fill(a){switch(this.kind){case
7:var
c=c6(a),e=c5(a);if(c===e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d===f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?d:f;break;case
13:this.data.fill(fc(a));break;default:this.data.fill(a);break}}compare(a,b){if(this.layout!==a.layout||this.kind!==a.kind){var
h=this.kind|this.layout<<8,i=a.kind|a.layout<<8;return i-h}if(this.dims.length!==a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!==a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!==e){if(!b)return Number.NaN;if(!Number.isNaN(d))return 1;if(!Number.isNaN(e))return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
13:for(var
c=0;c<this.data.length;c++){var
f=cZ(this.data[c]),g=cZ(a.data[c]);if(f<g)return-1;if(f>g)return 1;if(f!==g){if(!b)return Number.NaN;if(!Number.isNaN(f))return 1;if(!Number.isNaN(g))return-1}}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0}}class
gY
extends
eZ{offset(a){if(typeof
a!=="number")if(Array.isArray(a)&&a.length===1)a=a[0];else
s("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])bH();return a}get(a){return this.data[a]}set(a,b){this.data[a]=b;return 0}fill(a){this.data.fill(a);return 0}}function
e1(a,b,c,d){var
e=e3(a);if(cX(c)*e!==d.length)s("length doesn't match dims");if(b===0&&c.length===1&&e===1&&a!==13)return new
gY(a,b,c,d);return new
eZ(a,b,c,d)}var
bG="predef:Failure",cL="Failure";function
aD(a){if(!R[bG])R[bG]=[u,aj(cL),-3];fo(R[bG],a)}function
e2(a,b,c){var
k=a.read32s();if(k<0||k>16)aD("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&G,q=r>>8&1,j=[];if(c===bx)for(var
d=0;d<k;d++){var
p=a.read16u();if(p===C){var
u=a.read32u(),v=a.read32u();if(u!==0)aD("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=cX(j),h=g0(l,f),i=e1(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)aD("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=bb(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=c4(bb(g));i.set(d,m)}break;case
13:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
0:for(var
d=0;d<f;d++){var
m=c3(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=c3(a.read32s()),n=c3(a.read32s());i.set(d,[bA,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=c4(bb(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=c4(bb(g));i.set(d,[bA,o,n])}break}b[0]=(4+k)*4;return e1(l,q,j,h)}function
e0(a,b,c){return a.compare(b,c)}function
fk(a,b){return Math.imul(a,b)}function
W(a,b){b=fk(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=fk(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
hc(a,b){if((b&cJ)===cJ&&(b&0x03ff)!==0)b=0x7c01;else if(b===ao)b=0;return W(a,b)}function
hd(a,b){var
c=bO(b);if((c&cF)===cF&&(c&0x7fffff)!==0)c=0x7f800001;else if(c===(cR|0))c=0;a=W(a,c);return a}var
eH=0xfffff;function
hb(a,b){var
f=bP(b),d=c6(f),c=c5(f),e=0x7ff00000;if((c&e)===e&&(d|c&eH)!==0){c=e;d=0x00000001}else if(c===(cR|0)&&d===0)c=0;a=W(a,d);a=W(a,c);return a}function
e4(a){var
c=cX(a.dims),d=0,f=128;switch(a.kind){case
2:case
3:case
12:f=256;if(c>f)c=f;var
e=0,b=0;for(b=0;b+4<=c;b+=4){e=a.data[b+0]&G|(a.data[b+1]&G)<<8|(a.data[b+2]&G)<<16|a.data[b+3]<<24;d=W(d,e)}e=0;switch(c&3){case
3:e=(a.data[b+2]&G)<<16;case
2:e|=(a.data[b+1]&G)<<8;case
1:e|=a.data[b+0]&G;d=W(d,e)}break;case
4:case
5:if(c>f)c=f;var
e=0,b=0;for(b=0;b+2<=c;b+=2){e=a.data[b+0]&C|a.data[b+1]<<16;d=W(d,e)}if((c&1)!==0)d=W(d,a.data[b]&C);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=W(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=W(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=W(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=hd(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=hb(d,a.data[b]);break;case
13:if(c>f)c=f;for(var
b=0;b<c;b++)d=hc(d,a.data[b]);break}return d}function
hf(a,b){b[0]=4;return a.read32s()}function
hH(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:aD("input_value: native integer value too large");break;default:aD("input_value: ill-formed native integer")}}function
hs(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return bb(d)}function
hn(a,b,c){var
e=bd(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
hg(a,b,c){return a.compare(b)}function
hk(a){return a.lo32()^a.hi32()}var
fa={_j:{deserialize:hs,serialize:hn,fixed_length:8,compare:hg,hash:hk},_i:{deserialize:hf,fixed_length:4},_n:{deserialize:hH,fixed_length:4},_bigarray:{deserialize:function(a,b){return e2(a,b,"_bigarray")},serialize:e5,compare:e0,hash:e4},_bigarr02:{deserialize:function(a,b){return e2(a,b,bx)},serialize:e5,compare:e0,hash:e4}};function
e_(a){return fa[a.caml_custom]&&fa[a.caml_custom].compare}function
c9(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
c8(a){return a
instanceof
aA}var
em=255,ag=1000,bw=252,bC=1010;function
e$(a){if(a===null)return bC;if(typeof
a==="number")return ag;else if(c8(a))return bw;else if(c9(a))return 1252;else if(Array.isArray(a)&&a[0]===a[0]>>>0&&a[0]<=em){var
c=a[0]|0;return c===bA?0:c}else{var
b=12520;if(a
instanceof
String)return b;else if(typeof
a==="string")return b;else if(a
instanceof
Number)return ag;else if(a?.caml_custom)return 1255;else if(a?.compare)return 1256;else if(typeof
a==="function")return 1247;else if(typeof
a==="symbol")return 1251}return 1001}function
ht(a,b){if(a<b)return-1;if(a===b)return 0;return 1}function
h0(a,b){return a<b?-1:a>b?1:0}function
g4(a,b){a.t&6&&bL(a);b.t&6&&bL(b);return a.c<b.c?-1:a.c>b.c?1:0}function
e9(a,b,c){var
g=[];for(;;){if(!(c&&a===b)){var
e=e$(a),f=250;if(e===f){a=a[1];continue}var
h=e$(b);if(h===f){b=b[1];continue}if(e!==h){if(e===bC)return-1;if(h===bC)return 1;if(e===ag)return-1;if(h===ag)return 1;return e<h?-1:1}f="compare: functional value";switch(e){case
247:s(f);break;case
248:var
d=ht(a[2],b[2])|0;if(d!==0)return d;break;case
249:s(f);break;case
250:s("equal: got Forward_tag, should not happen");break;case
251:s("equal: abstract value");break;case
252:if(a!==b){var
d=g4(a,b)|0;if(d!==0)return d}break;case
253:s("equal: got Double_tag, should not happen");break;case
254:s("equal: got Double_array_tag, should not happen");break;case
255:s("equal: got Custom_tag, should not happen");break;case
1247:s(f);break;case
1255:var
j=e_(a);if(j!==e_(b))return a.caml_custom<b.caml_custom?-1:1;if(!j)s("compare: abstract value");var
d=j(a,b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1256:var
d=a.compare(b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!==b){if(!c)return Number.NaN;if(!Number.isNaN(a))return 1;if(!Number.isNaN(b))return-1}break;case
1010:return 0;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!==b)return c?1:Number.NaN;break;case
1251:if(a!==b)return c?1:Number.NaN;break;case
1252:var
a=aU(a),b=aU(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;default:if(hu(e)){s("compare: continuation value");break}if(a.length!==b.length)return a.length<b.length?-1:1;if(a.length>1)g.push(a,b,1);break}}if(g.length===0)return 0;var
i=g.pop();b=g.pop();a=g.pop();if(i+1<a.length)g.push(a,b,i+1);a=a[i];b=b[i]}}function
k(a,b){return+(e9(a,b,!1)===0)}function
g_(a,b,c,d){if(c>0)if(b===0&&(c>=a.l||a.t===2&&c>=a.c.length))if(d===0){a.c=e;a.t=2}else{a.c=at(c,String.fromCharCode(d));a.t=c===a.l?0:2}else{if(a.t!==4)bK(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}var
aS="+",ap="-",V=" ",D="0";function
da(a){a=aU(a);var
e=a.length;if(e>31)s("format_int: format too long");var
b={justify:aS,signstyle:ap,filler:V,alternate:!1,base:0,signedconv:!1,width:0,uppercase:!1,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=ap;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=D;break;case"#":b.alternate=!0;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;break;case"d":case"i":b.signedconv=!0;b.base=10;break;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=!0;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=!0;b.conv=c;break;case"E":case"F":case"G":b.signedconv=!0;b.uppercase=!0;b.conv=c.toLowerCase();break}}return b}var
eM="0x";function
c0(a,b){if(a.uppercase)b=b.toUpperCase();var
f=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!==ap))f++;var
g=a.alternate&&b!==D;if(g){if(a.base===8)f+=1;if(a.base===16)f+=2}var
c=e;if(a.justify===aS&&a.filler===V)for(var
d=f;d<a.width;d++)c+=V;if(a.signedconv)if(a.sign<0)c+=ap;else if(a.signstyle!==ap)c+=a.signstyle;if(g&&a.base===8)c+=D;if(g&&a.base===16)c+=a.uppercase?"0X":eM;if(a.justify===aS&&a.filler===D)for(var
d=f;d<a.width;d++)c+=D;c+=b;if(a.justify===ap)for(var
d=f;d<a.width;d++)c+=V;return aj(c)}var
cV="nan",af=".",bz=100;function
c1(a,b){function
o(a){var
b=new
DataView(new
ArrayBuffer(8));b.setFloat64(0,a);var
d=b.getUint32(0),f=b.getUint32(4),c=d>>>20&0x7ff,e=BigInt(d&eH)<<32n|BigInt(f);if(c===0)return[e,-1074];return[e|1n<<52n,c-1075]}function
m(a,b){var
d=o(a),e=d[0],c=1n,g=10n;if(b>=0)e*=g**BigInt(b);else
c=g**BigInt(-b);if(d[1]>=0)e<<=BigInt(d[1]);else
c<<=BigInt(-d[1]);var
f=e/c,h=e%c*2n;if(h>c||h===c&&f&1n)f+=1n;return f}function
q(a,b){var
c=m(a,b).toString();if(b===0)return c;if(c.length<=b)c=at(b+1-c.length,D)+c;return c.slice(0,c.length-b)+af+c.slice(c.length-b)}var
h="e";function
p(a,b){if(a===0)return(b>0?"0."+at(b,D):D)+"e+0";var
d=Math.floor(Math.log10(a));for(;;){var
c=m(a,b-d).toString();if(c.length===b+1){var
e=b>0?c.charAt(0)+af+c.slice(1):c;return e+h+(d<0?ap:aS)+Math.abs(d)}d+=c.length-(b+1)}}function
n(a,b){return b>bz?p(a,b):a.toExponential(b)}var
l=1e21;function
k(a,b){if(b>bz||a>=l)return q(a,b);return a.toFixed(b)}var
c,f=da(a),e=f.prec<0?6:f.prec;if(b<0||b===0&&1/b===Number.NEGATIVE_INFINITY){f.sign=-1;b=-b}if(Number.isNaN(b)){c=cV;f.filler=V}else if(!Number.isFinite(b)){c="inf";f.filler=V}else
switch(f.conv){case"e":var
c=n(b,e),d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+D+c.slice(d-1);break;case"f":c=k(b,e);break;case"g":e=e?e:1;c=n(b,e-1);var
j=c.indexOf(h),i=+c.slice(j+1);if(i<-4||b>=l||b.toFixed(0).length>e){var
d=j-1;while(c.charAt(d)===D)d--;if(c.charAt(d)===af)d--;c=c.slice(0,d+1)+c.slice(j);d=c.length;if(c.charAt(d-3)===h)c=c.slice(0,d-1)+D+c.slice(d-1);break}else{var
g=e;if(i<0){g-=i+1;c=k(b,g)}else
while(c=k(b,g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)===D)d--;if(c.charAt(d)===af)d--;c=c.slice(0,d+1)}}break}return c0(f,c)}var
cN="%d";function
bN(a,b){if(aU(a)===cN)return aj(e+b);var
c=da(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
d=b.toString(c.base);if(c.prec>=0){c.filler=V;var
f=c.prec-d.length;if(f>0)d=at(f,D)+d}return c0(c,d)}var
hJ=0;function
c2(){return hJ++}var
fu=new
ArrayBuffer(az);function
c_(a){if(df(a))return a;var
c=a.length<=fu.byteLength?new
Uint8Array(fu,0,a.length):new
Uint8Array(a.length);for(var
b=0;b<a.length;b++)c[b]=a.charCodeAt(b);return ft.decode(c)}var
dg=c.Deno?.build?.os==="windows"||c.process?.platform==="win32";function
bY(){return c.process?.versions?.node!==undefined}var
U="/",es=":";function
hY(){function
a(a){if(a.charAt(0)===U)return[e,a.slice(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||e,f=c.length>0&&c.charAt(1)!==es;if(b[2]||f){var
d=b[1]||e,g=b[2]||e;return[d,a.slice(d.length+g.length)]}return}return dg?b:a}var
di=hY(),hX={encode:a=>{var
j=a.length,f=0,h=0xe000,k=0x800;for(var
e=0;e<j;e++){var
b=a.charCodeAt(e);if(b<Q)f+=1;else if(b<k)f+=2;else if(b<cP||b>=h)f+=3;else if(b<a6&&e+1<j){var
g=a.charCodeAt(e+1);if(g>=a6&&g<h){f+=4;e++}else
f+=3}else
f+=3}var
c=new
Uint8Array(f),d=0;for(var
e=0;e<j;e++){var
b=a.charCodeAt(e);if(b<Q)c[d++]=b;else if(b<k){c[d++]=eT|b>>6;c[d++]=Q|b&P}else if(b<cP||b>=h){c[d++]=cI|b>>12;c[d++]=Q|b>>6&P;c[d++]=Q|b&P}else{var
m=0xef,l=0xbd;if(b<a6&&e+1<j){var
g=a.charCodeAt(e+1);if(g>=a6&&g<h){var
i=ea+((b&cE)<<10)+(g&cE);c[d++]=cS|i>>18;c[d++]=Q|i>>12&P;c[d++]=Q|i>>6&P;c[d++]=Q|i&P;e++}else{c[d++]=m;c[d++]=bB;c[d++]=l}}else{c[d++]=m;c[d++]=bB;c[d++]=l}}}return c}},hW=typeof
TextEncoder!=="undefined"?new
TextEncoder():hX;function
hP(a,b,c){var
d=String.fromCharCode;if(b===0&&c<=ek&&c===a.length)return d.apply(null,a);var
f=e;for(;0<c;b+=az,c-=az)f+=d.apply(null,a.slice(b,b+Math.min(c,az)));return f}function
hO(a){return aj(hP(a,0,a.length))}function
M(a){if(df(a))return aj(a);var
b=hW.encode(a);return hO(b)}function
S(a){fm(R["predef:Sys_error"],M(a))}function
fn(a,b){throw j([0,a].concat(b))}var
aP="EBADF",cU="EEXIST",ay="EINVAL",a7="EISDIR",cQ="ESPIPE",cG="ENOTEMPTY",aQ="ENOTDIR",aO="ENOENT",hZ=["E2BIG","EACCES","EAGAIN",aP,"EBUSY","ECHILD","EDEADLK","EDOM",cU,"EFAULT","EFBIG","EINTR",ay,"EIO",a7,"EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",aO,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",aQ,cG,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS",cQ,"ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
fw(a,b,c,d){var
f=hZ.indexOf(a);if(f<0){if(d==null)d=-9999;f=[0,-d]}var
g=[f,M(b||e),M(c||e)];return g}var
fl={};function
aV(a){return fl[a]}var
cC=", ",ev="Unix.Unix_error",a$=": ";function
f(a,b,c,d,e){var
f=aV(ev);if(a&&f)fn(f,fw(b,c,e));else{var
d=b+a$+d+cC+c;if(e!==undefined)d+=" '"+e+"'";S(d)}}function
fq(a){return a.slice(-1)!==U?a+U:a}function
de(){return!1}var
bM=function(){if(bY()&&c.process?.cwd)return c.process.cwd().replace(/\\/g,U);if(de()){var
a=c.os.getcwd();if(a[1]===0)return a[0]}return"/static"}();bM=fq(bM);function
hA(a,b){a=c_(a);if(a===e)f(b,aO,e,"No such file or directory",e);if(!di(a))a=bM+a;var
h=di(a),g=h[1].split(/[/\\]/),c=[];for(var
d=0;d<g.length;d++)switch(g[d]){case"..":c.pop();break;case".":break;case"":break;default:c.push(g[d]);break}c.unshift(h[0]);c.orig=a;return c}function
g5(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
aA(4,a,a.length)}var
ba="open",bF="no such file or directory";function
bf(a,b,c){if(b)f(b,aO,c||ba,bF,a);S(a+": No such file or directory")}function
e7(a){return new
aA(4,a,a.length)}function
X(a){return a.l}function
eX(){}class
aq
extends
eX{constructor(a){super();this.data=a}truncate(a){var
b=this.data,c=X(b);this.data=z(a|0);ar(b,0,this.data,0,Math.min(a,c))}length(){return X(this.data)}write(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=z(a+d),g=this.data;this.data=f;ar(g,0,this.data,0,e)}ar(e7(b),c,this.data,a,d);return d}read(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d>0){var
f=z(d|0);ar(this.data,a,f,0,d);b.set(dd(f),c);return d}return 0}}var
eD="write",a8="bad file descriptor",aR="invalid argument",ee="read",by="lseek",cK="truncate";class
gV{constructor(a,b,c){this.file=b;this.name=a;this.flags=c;this.offset=0;this.seeked=!1}err_closed(a,b){f(b,aP,a,a8)}length(a){if(this.file)return this.file.length();this.err_closed("length",a)}truncate(a,b){if(this.file){if(!(this.flags.wronly||this.flags.rdwr))f(b,ay,cK,aR);return this.file.truncate(a)}this.err_closed(cK,b)}write(a,b,c,d){if(this.file&&(this.flags.wronly||this.flags.rdwr)){if(this.flags.append)this.offset=this.file.length();var
e=this.offset;c=this.file.write(e,a,b,c);this.offset+=c;return c}this.err_closed(eD,d)}read(a,b,c,d){if(this.file&&!this.flags.wronly){var
e=this.offset;c=this.file.read(e,a,b,c);this.offset+=c;return c}this.err_closed(ee,d)}seek(a,b,c){switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)f(c,ay,by,aR);this.offset=a;this.seeked=!0;return a}pos(){return this.offset}close(a){if(!this.file)this.err_closed("close",a);this.file=undefined}check_stream_semantics(a){if(!this.file)return this.err_closed(a,1)}}var
eL="illegal operation on a directory",eQ="is a directory",bD="readdir",eh="directory not empty",aT="rename",eO="file already exists",bv="not a directory";class
eW{constructor(a,b){this.content={};this.root=a;this.lookupFun=b}nm(a){return this.root+a}create_dir_if_needed(a){var
d=a.split(U),c=e;for(var
b=0;b<d.length-1;b++){c+=d[b]+U;if(this.content[c])continue;this.content[c]=Symbol("directory")}}slash(a){return/\/$/.test(a)?a:a+U}lookup(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(M(this.root),M(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
aq(aB(b[1]))}}}exists(a,b){if(a===e)return 1;var
c=this.slash(a);if(this.content[c])return 1;if(!b)this.lookup(a);return this.content[a]?1:0}isFile(a){return this.exists(a)&&!this.is_dir(a)?1:0}rename_dir(a,b,c){var
e=this.slash(a),d=this.slash(b);if(b!==a&&d.startsWith(e))f(c,ay,aT,aR,this.nm(b));if(this.exists(b)){if(!this.is_dir(b))f(c,aQ,aT,bv,this.nm(b));if(this.readdir(b).length>0)f(c,cG,aT,eh,this.nm(b))}this.create_dir_if_needed(d);for(const
b
of
this.readdir(a))this.rename(e+b,d+b,c);delete
this.content[e]}rename(a,b,c){if(!this.exists(a))bf(this.nm(a),c,aT);if(this.is_dir(a))this.rename_dir(a,b,c);else{if(this.exists(b)&&this.is_dir(b))f(c,a7,aT,eQ,this.nm(b));if(b!==a){this.content[b]=this.content[a];delete
this.content[a]}}}mkdir(a,b,c){var
g="mkdir";if(this.exists(a))f(c,cU,g,eO,this.nm(a));var
d=/^(.*)\/[^/]+/.exec(a);d=d?.[1]||e;if(!this.exists(d))f(c,aO,g,bF,this.nm(a));if(!this.is_dir(d))f(c,aQ,g,bv,this.nm(a));this.create_dir_if_needed(this.slash(a))}rmdir(a,b){var
d=a===e?e:this.slash(a),c="rmdir";if(!this.exists(a))f(b,aO,c,bF,this.nm(a));if(!this.is_dir(a))f(b,aQ,c,bv,this.nm(a));for(var
g
in
this.content)if(g.startsWith(d)&&g!==d)f(b,cG,c,eh,this.nm(a));delete
this.content[d]}readdir(a,b){var
g=a===e?e:this.slash(a);if(!this.exists(a))bf(this.nm(a),b,bD);if(!this.is_dir(a))f(b,aQ,bD,bv,this.nm(a));var
j={},i=[];for(var
d
in
this.content)if(d.startsWith(g)&&d!==g){var
h=d.indexOf(U,g.length);if(h<0)h=undefined;var
c=d.slice(g.length,h);if(c&&!j[c]){j[c]=!0;i.push(c)}}return i}opendir(a,b){var
c=this.readdir(a,b),d=!1,e=0;return{readSync:function(){if(d)f(b,aP,bD,a8);if(e===c.length)return null;var
a=c[e];e++;return{name:a}},closeSync:function(){if(d)f(b,aP,bD,a8);d=!0;c=[]}}}is_dir(a){if(a===e)return!0;var
b=this.slash(a);return this.content[b]?1:0}unlink(a,b){var
c="unlink";if(!this.exists(a,!0))f(b,aO,c,bF,a);if(this.is_dir(a))f(b,a7,c,eQ,this.nm(a));delete
this.content[a];return 0}access(a,b,c){this.lookup(a);if(!this.exists(a))bf(this.nm(a),c,"access");return 0}open(a,b,c,d){var
e;this.lookup(a);if(this.content[a]){if(this.is_dir(a))f(d,a7,ba,eL,this.nm(a));if(b.create&&b.excl)f(d,cU,ba,eO,this.nm(a));e=this.content[a];if(b.truncate)e.truncate(0)}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
aq(z(0));e=this.content[a]}else
bf(this.nm(a),d,ba);return new
gV(this.nm(a),e,b)}truncate(a,b,c){var
d;this.lookup(a);if(this.content[a]){if(this.is_dir(a))f(c,a7,ba,eL,this.nm(a));d=this.content[a];d.truncate(b)}else
bf(this.nm(a),c,cK)}register(a,b){var
c;if(this.content[a])S(this.nm(a)+" : file already exists");if(c8(b))c=new
aq(b);else if(c9(b))c=new
aq(aB(b));else if(Array.isArray(b))c=new
aq(g5(b));else if(typeof
b==="string")c=new
aq(e6(b));else if(b.toString){var
d=aB(M(b.toString()));c=new
aq(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
S(this.nm(a)+" : registering file with invalid content type")}}function
g(a,b,c){var
d=aV(ev);if(b&&d){var
e=fw(a.code,c||a.syscall,a.path,a.errno);fn(d,e)}else
S(a.toString())}function
hp(a){if(a<0)a=Math.ceil(a);return new
d(a&y,Math.floor(a*bc)&y,Math.floor(a*bc*bc)&C)}function
dh(a,b){var
c;if(a.isFile())c=0;else if(a.isDirectory())c=1;else if(a.isCharacterDevice())c=2;else if(a.isBlockDevice())c=3;else if(a.isSymbolicLink())c=4;else if(a.isFIFO())c=5;else if(a.isSocket())c=6;return[0,a.dev,a.ino|0,c,a.mode&0o7777,a.nlink,a.uid,a.gid,a.rdev,b?hp(a.size):a.size|0,a.atimeMs/ag,a.mtimeMs/ag,a.ctimeMs/ag]}function
E(a){return a.length}function
bU(a,b){return a.charCodeAt(b)}function
h2(a){var
d=E(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=bU(a,b);return c}var
eN="illegal seek";class
cW
extends
eX{constructor(a,b){super();this.fs=require("node:fs");this.fd=a;this.flags=b;try{var
c=this.fs.fstatSync(a);b.noSeek=c.isCharacterDevice()||c.isFIFO()||c.isSocket();this.offset=0}catch(f){b.noSeek=!0;this.offset=0}this.seeked=!1}truncate(a,b){try{this.fs.ftruncateSync(this.fd,a)}catch(f){g(f,b)}}isatty(){var
a=require("node:tty");return a.isatty(this.fd)?1:0}length(){try{return this.fs.fstatSync(this.fd).size}catch(f){S(f.toString())}}write(a,b,c,d){try{if(this.flags.append&&!this.flags.noSeek)this.offset=this.length();if(this.flags.noSeek||!this.seeked)var
e=this.fs.writeSync(this.fd,a,b,c);else
var
e=this.fs.writeSync(this.fd,a,b,c,this.offset);this.offset+=e}catch(f){g(f,d)}return e}read(a,b,c,d){try{if(this.flags.noSeek||!this.seeked)var
e=this.fs.readSync(this.fd,a,b,c);else
var
e=this.fs.readSync(this.fd,a,b,c,this.offset);this.offset+=e;return e}catch(f){g(f,d)}}seek(a,b,c){if(this.flags.noSeek)f(c,cQ,by,eN);switch(b){case
0:break;case
1:a+=this.offset;break;case
2:a+=this.length();break}if(a<0)f(c,ay,by,aR);this.offset=a;this.seeked=!0;return this.offset}pos(){return this.offset}stat(a){try{var
b=this.fs.fstatSync(this.fd);return dh(b,a)}catch(f){g(f,1)}}chmod(a){try{this.fs.fchmodSync(this.fd,a);return 0}catch(f){g(f,1)}}sync(){try{this.fs.fsyncSync(this.fd);return 0}catch(f){g(f,1)}}close(a){try{this.fs.closeSync(this.fd);return 0}catch(f){g(f,a)}}check_stream_semantics(a){try{var
b=this.fs.fstatSync(this.fd)}catch(f){g(f,1,a)}if(!(b.isFile()||b.isCharacterDevice()||b.isFIFO()||b.isSocket()))f(1,ay,a,aR)}}class
eY{constructor(a){this.fs=require("node:fs");this.root=a}nm(a){return this.root+a}exists(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}}isFile(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){S(f.toString())}}mkdir(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){g(f,c)}}rmdir(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){g(f,b)}}readdir(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){g(f,b)}}is_dir(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){S(f.toString())}}unlink(a,b){try{this.fs.unlinkSync(this.nm(a));return 0}catch(f){g(f,b)}}utimes(a,b,c,d){try{if(b===0&&c===0){b=Date.now()/ag;c=b}this.fs.utimesSync(this.nm(a),b,c);return 0}catch(f){g(f,d)}}truncate(a,b,c){try{this.fs.truncateSync(this.nm(a),b);return 0}catch(f){g(f,c)}}access(a,b,c){var
d=this.fs.constants,e=0;for(var
f
in
b)switch(f){case"r":e|=d.R_OK;break;case"w":e|=d.W_OK;break;case"x":e|=dg?d.R_OK:d.X_OK;break;case"f":e|=d.F_OK;break}try{this.fs.accessSync(this.nm(a),e);return 0}catch(f){g(f,c)}}open(a,b,c,d){var
f=this.fs.constants,e=0;for(var
i
in
b)switch(i){case"rdonly":e|=f.O_RDONLY;break;case"wronly":e|=f.O_WRONLY;break;case"rdwr":e|=f.O_RDWR;break;case"append":e|=f.O_APPEND;break;case"create":e|=f.O_CREAT;break;case"truncate":e|=f.O_TRUNC;break;case"excl":e|=f.O_EXCL;break;case"binary":e|=f.O_BINARY;break;case"text":e|=f.O_TEXT;break;case"nonblock":e|=f.O_NONBLOCK;break;case"noctty":e|=f.O_NOCTTY;break;case"dsync":e|=f.O_DSYNC;break;case"sync":e|=f.O_SYNC;break}try{var
h=this.fs.openSync(this.nm(a),e,c);return new
cW(h,b)}catch(f){g(f,d)}}slash(a){return/\/$/.test(a)?a:a+U}rename(a,b,c){if(dg)try{var
d=this.nm(b),e=this.nm(a),i,h;if((i=this.fs.statSync(d,{throwIfNoEntry:!1}))&&(h=this.fs.statSync(e,{throwIfNoEntry:!1}))&&h.isDirectory())if(i.isDirectory()){if(!this.slash(d).startsWith(this.slash(e)))try{this.fs.rmdirSync(d)}catch{}}else{var
f=new
Error(`ENOTDIR: not a directory, rename '${e}' -> '${d}'`);throw Object.assign(f,{errno:-20,code:aQ,syscall:aT,path:d})}this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){g(f,c)}else
try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){g(f,c)}}stat(a,b,c){try{var
d=this.fs.statSync(this.nm(a));return dh(d,b)}catch(f){g(f,c)}}lstat(a,b,c){try{var
d=this.fs.lstatSync(this.nm(a));return dh(d,b)}catch(f){g(f,c)}}chmod(a,b,c){try{this.fs.chmodSync(this.nm(a),b);return 0}catch(f){g(f,c)}}link(a,b,c){try{this.fs.linkSync(this.nm(a),this.nm(b));return 0}catch(f){g(f,c)}}symlink(a,b,c,d){try{this.fs.symlinkSync(b,this.nm(c),a===0?null:a[1]?"dir":"file");return 0}catch(f){g(f,d)}}readlink(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return M(c)}catch(f){g(f,b)}}opendir(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){g(f,b)}}}class
gX{}function
fe(a){var
b=di(a);if(!b)return;return b[0]+U}var
aW=fe(bM)||aD("unable to compute caml_root"),aH=[];if(bY())aH.push({path:aW,device:new
eY(aW)});else if(de())aH.push({path:aW,device:new
gX(aW)});else
aH.push({path:aW,device:new
eW(aW)});a="/static/";aH.push({path:a,device:new
eW(a)});function
fx(a,b){var
h=hA(a,b),a=h.join(U),g=fq(a),d;for(var
e=0;e<aH.length;e++){var
c=aH[e];if(g.startsWith(c.path)&&(!d||d.path.length<c.path.length))d={path:c.path,device:c.device,rest:a.slice(c.path.length,a.length)}}if(!d&&bY()){var
f=fe(a);if(f?.match(/^[a-zA-Z]:\/$/)){var
c={path:f,device:new
eY(f)};aH.push(c);d={path:c.path,device:c.device,rest:a.slice(c.path.length,a.length)}}}if(d)return d;S("no device found for "+g)}function
g8(a,b){var
c=fx(a);if(!c.device.register)aD("cannot register file");c.device.register(c.rest,b);return 0}function
fr(a,b){var
a=M(a),b=aj(b);return g8(a,b)}function
ha(){var
b=c.jsoo_fs_tmp;if(b)for(var
a=0;a<b.length;a++)fr(b[a].name,b[a].content);c.jsoo_create_file=fr;c.jsoo_fs_tmp=[];return 0}function
fd(a){return[0]}var
eF="infinity";function
he(a,b,c){if(!Number.isFinite(a)){if(Number.isNaN(a))return M(cV);return M(a>0?eF:"-infinity")}var
k=a===0&&1/a===Number.NEGATIVE_INFINITY?1:a>=0?0:1;if(k)a=-a;var
f=0;if(a===0);else if(a<1)while(a<1&&f>-1022){a*=2;f--}else
while(a>=2){a/=2;f++}var
l=f<0?e:aS,g=e;if(k)g=ap;else
switch(c){case
43:g=aS;break;case
32:g=V;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(af);if(j<0)d+=af+at(b,D);else{var
h=j+1+b;if(d.length<h)d+=at(h-d.length,D);else
d=d.slice(0,h)}}return M(g+eM+d+"p"+l+f.toString(10))}function
hm(a){return+a.isZero()}function
hq(a){return new
d(a&y,a>>24&y,a>>31&C)}function
hr(a){return a.toInt()}function
hl(a){return+a.isNeg()}function
ho(a){return a.neg()}function
hj(a,b){var
c=da(a);if(c.signedconv&&hl(b)){c.sign=-1;b=ho(b)}var
d=e,i=hq(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(hr(g.modulus))+d}while(!hm(b));if(c.prec>=0){c.filler=V;var
f=c.prec-d.length;if(f>0)d=at(f,D)+d}return c0(c,d)}function
ff(a){return a.slice(1)}function
fg(a,b,c){return a[c_(b)].apply(a,ff(c))}function
hw(a,b){switch(b.length){case
1:return new
a();case
2:return new
a(b[1]);case
3:return new
a(b[1],b[2]);case
4:return new
a(b[1],b[2],b[3]);case
5:return new
a(b[1],b[2],b[3],b[4]);case
6:return new
a(b[1],b[2],b[3],b[4],b[5]);case
7:return new
a(b[1],b[2],b[3],b[4],b[5],b[6]);case
8:return new
a(b[1],b[2],b[3],b[4],b[5],b[6],b[7])}function
c(){return a.apply(this,ff(b))}c.prototype=a.prototype;return new
c()}function
hx(a){var
d=a.length,c=new
Array(d+1);c[0]=0;for(var
b=0;b<d;b++)c[b+1]=a[b];return c}var
bJ=as;function
ah(c,b){return function(...a){a.length=c;return bJ(b,a)}}function
hy(a){var
c=0;for(var
b=a.length-1;b>=0;b--){var
d=a[b];c=[0,d,c]}return c}function
hz(a){var
b=[];for(;a!==0;a=a[2])b.push(a[1]);return b}function
hC(){return 0}function
eV(a){this.id=a}class
hB{constructor(){this.map=new
c.WeakMap();this.opened=new
c.Set()}close(a){this.opened.delete(a)}get(a){return this.map.get(a)}set(a,b){if(b.opened)this.opened.add(a);return this.map.set(a,b)}all(){return this.opened.values()}}var
bQ=new
hB();function
c$(a){return bQ.get(a)}function
ai(a){var
b=c$(a);if(!b.opened)return 0;if(!b.buffer||b.buffer_curr===0)return 0;if(b.output)b.output(bV(b.buffer,0,b.buffer_curr));else
for(var
c=0;c<b.buffer_curr;)c+=b.file.write(b.buffer,c,b.buffer_curr-c,!1);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}var
bR=[],c7=65536;function
hT(a,b){return null}function
hS(a,b){if(b.altname)try{var
d=require("node:fs"),c=d.openSync(b.altname,"rs");return new
cW(c,b)}catch(f){}return new
cW(a,b)}var
bW=new
Array(3);class
gW
extends
aq{constructor(a,b){super(z(0));var
c=b=>a=>b(a.length>0&&a.charCodeAt(a.length-1)===10?a.slice(0,-1):a);if(a===1&&typeof
console.log==="function")this.log=c(console.log);else if(a===2&&typeof
console.error==="function")this.log=c(console.error);else if(typeof
console.log==="function")this.log=c(console.log);else
this.log=a=>0;this.flags=b}length(){return 0}truncate(a,b){f(b,ay,"ftruncate",aR)}write(a,b,c,d){if(this.log){var
e=z(c);ar(e7(a),b,e,0,c);this.log(e.toUtf16());return c}f(d,aP,eD,a8)}read(a,b,c,d){f(d,aP,ee,a8)}seek(a,b,c){f(c,cQ,by,eN)}pos(){return-1}close(){this.log=undefined}check_stream_semantics(a){}}function
bX(a,b){if(b===undefined)b=bW.length;bW[b]={file:a};return b|0}function
h1(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;d.wronly=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
e=fx(a),f=e.device.open(e.rest,d,c);return bX(f,undefined)}(function(){var
c=bY(),d=!c&&de(),b=c||d?1:2;function
a(a,b){if(c)return hS(a,b);if(d)return hT(a,b);return new
gW(a,b)}bX(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:!0}),0);bX(a(1,{buffered:b,wronly:1,isCharacterDevice:!0}),1);bX(a(2,{buffered:b,wronly:1,isCharacterDevice:!0}),2)}());var
eA=" doesn't exist",eE="fd ";function
hD(a){var
c=bW[a];if(c===undefined)S(eE+a+eA);var
d=c.file,b=new
eV(a),f=null,e={file:d,offset:d.pos(),fd:a,opened:!0,out:!1,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(c7),refill:f};bQ.set(b,e);if(a<=2&&!bR[a])bR[a]=b;return b}function
fh(a){var
d=bW[a];if(d===undefined)S(eE+a+eA);var
b=d.file,c=new
eV(a),e=b.flags.buffered!==undefined?b.flags.buffered:1,f={file:b,offset:b.pos(),fd:a,opened:!0,out:!0,buffer_curr:0,buffer:new
Uint8Array(c7),buffered:e};bQ.set(c,f);if(a<=2&&!bR[a])bR[a]=c;return c}function
hE(){var
a=0,d=bQ.all();for(var
c
of
d){var
b=c$(c);if(b.opened&&b.out)a=[0,c,a]}return a}function
hG(a,b,c,d){var
e=c$(a);if(!e.opened)S("Cannot output to a closed channel");b=b.subarray(c,c+d);if(e.buffer_curr+b.length>e.buffer.length){var
g=new
Uint8Array(e.buffer_curr+b.length);g.set(e.buffer);e.buffer=g}switch(e.buffered){case
0:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;ai(a);break;case
1:e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)ai(a);break;case
2:var
f=b.lastIndexOf(10);if(f<0){e.buffer.set(b,e.buffer_curr);e.buffer_curr+=b.length;if(e.buffer_curr>=e.buffer.length)ai(a)}else{e.buffer.set(b.subarray(0,f+1),e.buffer_curr);e.buffer_curr+=f+1;ai(a);e.buffer.set(b.subarray(f+1),e.buffer_curr);e.buffer_curr+=b.length-f-1}break}return 0}function
hF(a,b,c,d){var
b=dd(b);return hG(a,b,c,d)}function
fi(a,b,c,d){return hF(a,aB(b),c,d)}function
fj(a,b){var
c=aj(String.fromCharCode(b));fi(a,c,0,1);return 0}function
be(a,b){return+(e9(a,b,!1)!==0)}function
hI(a){if(a===null)return null;return typeof
a==="number"?a:a.slice()}function
bS(a){if(a===null)return bC;else if(Array.isArray(a)&&a[0]===a[0]>>>0)return a[0];else if(c8(a))return bw;else if(c9(a))return bw;else if(a
instanceof
Function||typeof
a==="function")return 247;else if(a?.caml_custom)return em;else
return ag}var
fv,aE={},eq="predef:";function
g2(a){var
d={},c=-1;if(a)for(var
b=1;b<a.length;b++){var
e=a[b][1],h=e[0],g=c_(e[1]),f=a[b][2];c=Math.max(c,f);d[h?eq+g:g]=f}d.next_idx=c+1;return d}function
b(a,b){var
d=eq+b;if(fv){var
e=bJ(fv,[[1,b]]);R[e+1]=a}else if(aE.symbols){if(!aE.symidx)aE.symidx=g2(aE.symbols);var
c=aE.symidx[d];if(c===undefined){c=aE.symidx.next_idx++;aE.symidx[d]=c}R[c+1]=a}R[d]=a}function
db(a,b){fl[aU(a)]=b;return 0}function
hN(){s(cM)}function
J(a,b){if(b>>>0>=E(a))hN();return bU(a,b)}function
L(a){a.t&6&&bL(a);return aj(a.c)}function
hQ(){return 0x7fffffff/4|0}function
hR(a){return c7}function
dc(a){var
b=1;while(a?.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
aF(a,b,c){return{joo_tramp:a,joo_args:b,joo_direct:c}}var
cT="jsError";function
aG(a){{if(Array.isArray(a))return a;var
b,d="predef:Stack_overflow";if(c.RangeError&&a
instanceof
c.RangeError&&a.message?.match(/maximum call stack/i))b=R[d];else if(c.InternalError&&a
instanceof
c.InternalError&&a.message?.match(/too much recursion/i))b=R[d];else if(a
instanceof
c.Error&&aV(cT))b=[0,aV(cT),a];else
b=[0,R[bG],M(String(a))];if(a
instanceof
c.Error)b.js_error=a;return b}}function
hv(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}var
a_='"',el="_";function
g$(a){var
b=e;if(a[0]===0){b+=a[1][1];if(a.length===3&&a[2][0]===0&&hv(a[1]))var
f=a[2],g=1;else
var
g=2,f=a;b+="(";for(var
d=g;d<f.length;d++){if(d>g)b+=cC;var
c=f[d];if(typeof
c==="number")b+=c.toString();else if(c
instanceof
aA)b+=a_+c.toString()+a_;else if(typeof
c==="string")b+=a_+c.toString()+a_;else
b+=el}b+=")"}else if(a[0]===u)b+=a[1];return b}var
cO="Fatal error: exception ",et="Pervasives.do_at_exit",eb="Printexc.handle_uncaught_exception";function
fb(a){if(Array.isArray(a)&&(a[0]===0||a[0]===u)){var
c=aV(eb);if(c)bJ(c,[a,!1]);else{var
d=g$(a),b=aV(et);if(b)bJ(b,[0]);console.error(cO+d);if(a.js_error)throw a.js_error}}else
throw a}var
eo="error";function
hM(){var
d=c.process;if(d?.on)d.on("uncaughtException",function(a,b){fb(a);d.exit(2)});else if(c.addEventListener)c.addEventListener(eo,function(a){if(a.error)fb(a.error)})}hM();function
m(a,b){return(a.l>=0?a.l:a.l=a.length)===1?a(b):as(a,[b])}function
B(a,b,c){return(a.l>=0?a.l:a.l=a.length)===2?a(b,c):as(a,[b,c])}function
gU(a,b,c,d,e){return(a.l>=0?a.l:a.l=a.length)===4?a(b,c,d,e):as(a,[b,c,d,e])}function
cA(a,b,c,d,e,f){return(a.l>=0?a.l:a.l=a.length)===5?a(b,c,d,e,f):as(a,[b,c,d,e,f])}function
gT(a,b,c,d,e,f,g,h){return(a.l>=0?a.l:a.l=a.length)===7?a(b,c,d,e,f,g,h):as(a,[b,c,d,e,f,g,h])}a=0;ha();a="Undefined_recursive_module";var
dq=[u,a,-12];b(dq,a);a="Assert_failure";var
p=[u,a,-11];b(p,a);a="Sys_blocked_io";b([u,a,-10],a);a="Stack_overflow";var
dn=[u,a,-9];b(dn,a);a="Match_failure";var
dm=[u,a,-8];b(dm,a);a="Not_found";b([u,a,-7],a);a="Division_by_zero";b([u,a,-6],a);a="End_of_file";b([u,a,-5],a);a="Invalid_argument";var
dj=[u,a,-4];b(dj,a);var
dl=[u,cL,-3];b(dl,cL);a="Sys_error";var
dp=[u,a,-2];b(dp,a);a="Out_of_memory";var
bZ=[u,a,-1];b(bZ,a);function
o(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,o(a[1])];case
1:return[1,o(a[1])];case
2:return[2,o(a[1])];case
3:return[3,o(a[1])];case
4:return[4,o(a[1])];case
5:return[5,o(a[1])];case
6:return[6,o(a[1])];case
7:return[7,o(a[1])];case
8:var
b=a[1];return[8,b,o(a[2])];case
9:b=a[1];return[9,b,b,o(a[3])];case
10:return[10,o(a[1])];case
11:return[11,o(a[1])];case
12:return[12,o(a[1])];case
13:return[13,o(a[1])];default:return[14,o(a[1])]}}function
A(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,A(a[1],b)];case
1:return[1,A(a[1],b)];case
2:return[2,A(a[1],b)];case
3:return[3,A(a[1],b)];case
4:return[4,A(a[1],b)];case
5:return[5,A(a[1],b)];case
6:return[6,A(a[1],b)];case
7:return[7,A(a[1],b)];case
8:var
c=a[1];return[8,c,A(a[2],b)];case
9:c=a[2];var
d=a[1];return[9,d,c,A(a[3],b)];case
10:return[10,A(a[1],b)];case
11:return[11,A(a[1],b)];case
12:return[12,A(a[1],b)];case
13:return[13,A(a[1],b)];default:return[14,A(a[1],b)]}}function
n(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,n(a[1],b)];case
1:return[1,n(a[1],b)];case
2:var
e=a[1];return[2,e,n(a[2],b)];case
3:e=a[1];return[3,e,n(a[2],b)];case
4:e=a[3];var
c=a[2],d=a[1];return[4,d,c,e,n(a[4],b)];case
5:d=a[3];e=a[2];c=a[1];return[5,c,e,d,n(a[4],b)];case
6:c=a[3];d=a[2];e=a[1];return[6,e,d,c,n(a[4],b)];case
7:e=a[3];c=a[2];d=a[1];return[7,d,c,e,n(a[4],b)];case
8:d=a[3];e=a[2];c=a[1];return[8,c,e,d,n(a[4],b)];case
9:c=a[1];return[9,c,n(a[2],b)];case
10:return[10,n(a[1],b)];case
11:c=a[1];return[11,c,n(a[2],b)];case
12:c=a[1];return[12,c,n(a[2],b)];case
13:c=a[2];d=a[1];return[13,d,c,n(a[3],b)];case
14:c=a[2];d=a[1];return[14,d,c,n(a[3],b)];case
15:return[15,n(a[1],b)];case
16:return[16,n(a[1],b)];case
17:c=a[1];return[17,c,n(a[2],b)];case
18:c=a[1];return[18,c,n(a[2],b)];case
19:return[19,n(a[1],b)];case
20:c=a[2];d=a[1];return[20,d,c,n(a[3],b)];case
21:c=a[1];return[21,c,n(a[2],b)];case
22:return[22,n(a[1],b)];case
23:c=a[1];return[23,c,n(a[2],b)];default:c=a[2];d=a[1];return[24,d,c,n(a[3],b)]}}function
dk(a){throw j([0,dl,a],1)}function
ak(a){throw j([0,dj,a],1)}function
bg(a){return 0<=a?a:-a|0}hD(0);fh(1);var
T=fh(2);function
aX(a,b){fi(a,b,0,E(b))}function
dr(a){aX(T,a);fj(T,10);return ai(T)}function
b0(a){a=hE(0);for(;;){if(!a)return 0;var
b=a[2],c=a[1];try{ai(c);a=b}catch(f){a=aG(f);if(a[1]!==dp)throw j(a,0);a=b}}}db(et,b0);var
aY=(4*hQ(0)|0)-1|0;hR(0);function
bh(a){return a?a[1]:ak("option is None")}function
b2(a){return a?a[1]:dk("hd")}function
b3(a){var
b=0;for(;;){if(!a)return b;b=[0,a[1],b];a=a[2]}}function
au(a,b){var
c=z(a);g_(c,0,a,b);return c}function
ds(a,b,c){a:{if(0<=b&&0<=c&&(X(a)-c|0)>=b){var
d=z(c);ar(a,b,d,0,c);break a}d=ak("String.sub / Bytes.sub")}return L(d)}function
dt(a,b,c,d,e){if(0<=e&&0<=b&&(X(a)-e|0)>=b&&0<=d&&(X(c)-e|0)>=d){ar(a,b,c,d,e);return}return ak("Bytes.blit")}function
Y(a,b,c,d,e){if(0<=e&&0<=b&&(E(a)-e|0)>=b&&0<=d&&(X(c)-e|0)>=d){bI(a,b,c,d,e);return}return ak("String.blit / Bytes.blit_string")}function
du(a,b){var
d=a[2],c=a[1][2];for(;;){if(c>=(d+b|0))break;c=2*c|0}b=aY<c?(d+b|0)<=aY?aY:(dk("Buffer.add: cannot grow buffer"),c):c;c=z(b);dt(a[1][1],0,c,0,a[2]);a[1]=[0,c,b]}function
aZ(a,b){var
d=E(b),c=d<0,c=c||(E(b)-d|0)<0;if(c)ak("Buffer.add_substring");c=a[2];var
e=a[1],f=c+d|0,g=e[1];if(e[2]<f){du(a,d);Y(b,0,a[1][1],a[2],d)}else
bI(b,0,g,c,d);a[2]=f}function
b4(a){return 5===a[2]?12:-6}function
dv(a){return[0,0,z(a)]}function
dw(a,b){var
c=X(a[2]),b=a[1]+b|0;if(c<b){var
d=c*2|0,b=b<=d?d:b,b=z(b);dt(a[2],0,b,0,c);a[2]=b}}function
aI(a,b){dw(a,1);aC(a[2],a[1],b);a[1]=a[1]+1|0}function
w(a,b){var
c=E(b);dw(a,c);Y(b,0,a[2],a[1],c);a[1]=a[1]+c|0}function
dx(a){return ds(a[2],0,a[1])}function
dy(a){if(typeof
a==="number")switch(a){case
0:return"@]";case
1:return"@}";case
2:return"@?";case
3:return"@\n";case
4:return"@.";case
5:return"@@";default:return"@%"}return 2===a[0]?"@"+L(au(1,a[1])):a[1]}var
eU="%ni",eg="%li",er="%Li",d_="%i";function
b5(a,b){for(;;){if(typeof
b==="number")return;switch(b[0]){case
0:b=b[1];w(a,"%c");break;case
1:b=b[1];w(a,"%s");break;case
2:b=b[1];w(a,d_);break;case
3:b=b[1];w(a,eg);break;case
4:b=b[1];w(a,eU);break;case
5:b=b[1];w(a,er);break;case
6:b=b[1];w(a,"%f");break;case
7:b=b[1];w(a,"%B");break;case
8:var
c=b[2],b=b[1];w(a,"%{");b5(a,b);w(a,"%}");b=c;break;case
9:c=b[3];b=b[1];w(a,"%(");b5(a,b);w(a,"%)");b=c;break;case
10:b=b[1];w(a,"%a");break;case
11:b=b[1];w(a,"%t");break;case
12:b=b[1];w(a,"%?");break;case
13:b=b[1];w(a,"%r");break;default:b=b[1];w(a,"%_r")}}}function
r(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,r(a[1])];case
1:return[1,r(a[1])];case
2:return[2,r(a[1])];case
3:return[3,r(a[1])];case
4:return[4,r(a[1])];case
5:return[5,r(a[1])];case
6:return[6,r(a[1])];case
7:return[7,r(a[1])];case
8:var
b=a[1];return[8,b,r(a[2])];case
9:b=a[2];var
c=a[1];return[9,b,c,r(a[3])];case
10:return[10,r(a[1])];case
11:return[11,r(a[1])];case
12:return[12,r(a[1])];case
13:return[13,r(a[1])];default:return[14,r(a[1])]}}function
x(a){if(typeof
a==="number")return[0,,function(a){},,function(a){}];switch(a[0]){case
0:a=x(a[1]);var
b=a[2];return[0,,function(a){b(0)},,a[4]];case
1:a=x(a[1]);var
c=a[2];return[0,,function(a){c(0)},,a[4]];case
2:a=x(a[1]);var
d=a[2];return[0,,function(a){d(0)},,a[4]];case
3:a=x(a[1]);var
e=a[2];return[0,,function(a){e(0)},,a[4]];case
4:a=x(a[1]);var
f=a[2];return[0,,function(a){f(0)},,a[4]];case
5:a=x(a[1]);var
g=a[2];return[0,,function(a){g(0)},,a[4]];case
6:a=x(a[1]);var
h=a[2];return[0,,function(a){h(0)},,a[4]];case
7:a=x(a[1]);var
i=a[2];return[0,,function(a){i(0)},,a[4]];case
8:a=x(a[2]);var
j=a[2];return[0,,function(a){j(0)},,a[4]];case
9:var
k=a[2],l=a[1],a=x(a[3]),m=a[4],n=a[2],a=x(t(r(l),k)),o=a[4],p=a[2];return[0,,function(a){p(0);n(0)},,function(a){o(0);m(0)}];case
10:a=x(a[1]);var
q=a[2];return[0,,function(a){q(0)},,a[4]];case
11:a=x(a[1]);var
s=a[2];return[0,,function(a){s(0)},,a[4]];case
12:a=x(a[1]);var
u=a[2];return[0,,function(a){u(0)},,a[4]];case
13:a=x(a[1]);var
v=a[4],w=a[2];return[0,,function(a){w(0)},,function(a){v(0)}];default:a=x(a[1]);var
y=a[4],z=a[2];return[0,,function(a){z(0)},,function(a){y(0)}]}}var
a="camlinternalFormat.ml",fA=[0,a,850,23],fB=[0,a,837,26],fC=[0,a,847,28],fD=[0,a,815,21],fE=[0,a,819,21],fF=[0,a,823,19],fG=[0,a,827,22],fH=[0,a,832,30],fI=[0,a,851,23],fJ=[0,a,836,26],fK=[0,a,846,28],fL=[0,a,814,21],fM=[0,a,818,21],fN=[0,a,822,19],fO=[0,a,826,22],fP=[0,a,831,30];function
t(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:a=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
1:a=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
2:a=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
3:a=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
4:a=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
5:a=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
6:a=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
7:a=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break g}break;case
8:var
c=a[2],a=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
d=b[1],b=t(c,b[2]);return[8,t(a,d),b];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw j([0,p,fJ],1);case
9:d=a[3];c=a[2];a=a[1];if(typeof
b!=="number")switch(b[0]){case
9:var
e=b[3],f=b[2],b=b[1],b=x(t(r(c),b)),c=b[4];b[2].call(null,0);c(0);return[9,a,f,t(d,e)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f}throw j([0,p,fK],1);case
10:a=a[1];if(typeof
b!=="number"&&10===b[0])return[10,t(a,b[1])];throw j([0,p,fL],1);case
11:a=a[1];if(typeof
b!=="number")switch(b[0]){case
11:return[11,t(a,b[1])];case
10:break a}throw j([0,p,fM],1);case
12:a=a[1];if(typeof
b!=="number")switch(b[0]){case
12:return[12,t(a,b[1])];case
10:break a;case
11:break b}throw j([0,p,fN],1);case
13:a=a[1];if(typeof
b!=="number")switch(b[0]){case
13:return[13,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c}throw j([0,p,fO],1);default:a=a[1];if(typeof
b!=="number")switch(b[0]){case
14:return[14,t(a,b[1])];case
10:break a;case
11:break b;case
12:break c;case
13:break d}throw j([0,p,fP],1)}throw j([0,p,fI],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw j([0,p,fA],1)}}throw j([0,p,fC],1)}throw j([0,p,fB],1)}throw j([0,p,fH],1)}throw j([0,p,fG],1)}throw j([0,p,fF],1)}throw j([0,p,fE],1)}throw j([0,p,fD],1)}var
v=[u,"CamlinternalFormat.Type_mismatch",c2(0)],a9="true",cD="false";function
fy(a){return a?a9:cD}function
bi(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw j(v,1)}function
a0(a,b,c){c=bi(a,c);if(typeof
b!=="number")return[0,c[1],[0,b[1]],c[2]];if(!b)return[0,c[1],0,c[2]];b=c[2];if(typeof
b!=="number"&&2===b[0])return[0,c[1],1,b[1]];throw j(v,1)}function
l(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){b=l(a[1],b[1]);return[0,[0,b[1]],b[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){b=l(a[1],b[1]);return[0,[1,b[1]],b[2]]}break;case
2:var
c=a[2],b=bi(a[1],b),a=b[2],b=b[1];if(typeof
a!=="number"&&1===a[0]){a=l(c,a[1]);return[0,[2,b,a[1]],a[2]]}throw j(v,1);case
3:c=a[2];a=bi(a[1],b);b=a[2];a=a[1];if(typeof
b!=="number"&&1===b[0]){b=l(c,b[1]);return[0,[3,a,b[1]],b[2]]}throw j(v,1);case
4:c=a[4];var
e=a[1],b=a0(a[2],a[3],b),a=b[3],d=b[1];if(typeof
a!=="number"&&2===a[0]){b=b[2];a=l(c,a[1]);return[0,[4,e,d,b,a[1]],a[2]]}throw j(v,1);case
5:d=a[4];e=a[1];a=a0(a[2],a[3],b);b=a[3];c=a[1];if(typeof
b!=="number"&&3===b[0]){a=a[2];b=l(d,b[1]);return[0,[5,e,c,a,b[1]],b[2]]}throw j(v,1);case
6:c=a[4];e=a[1];b=a0(a[2],a[3],b);a=b[3];d=b[1];if(typeof
a!=="number"&&4===a[0]){b=b[2];a=l(c,a[1]);return[0,[6,e,d,b,a[1]],a[2]]}throw j(v,1);case
7:d=a[4];e=a[1];a=a0(a[2],a[3],b);b=a[3];c=a[1];if(typeof
b!=="number"&&5===b[0]){a=a[2];b=l(d,b[1]);return[0,[7,e,c,a,b[1]],b[2]]}throw j(v,1);case
8:c=a[4];e=a[1];b=a0(a[2],a[3],b);a=b[3];d=b[1];if(typeof
a!=="number"&&6===a[0]){b=b[2];a=l(c,a[1]);return[0,[8,e,d,b,a[1]],a[2]]}throw j(v,1);case
9:d=a[2];a=bi(a[1],b);b=a[2];a=a[1];if(typeof
b!=="number"&&7===b[0]){b=l(d,b[1]);return[0,[9,a,b[1]],b[2]]}throw j(v,1);case
10:a=l(a[1],b);return[0,[10,a[1]],a[2]];case
11:d=a[1];a=l(a[2],b);return[0,[11,d,a[1]],a[2]];case
12:d=a[1];a=l(a[2],b);return[0,[12,d,a[1]],a[2]];case
13:if(typeof
b!=="number"&&8===b[0]){d=b[1];b=b[2];e=a[3];c=a[1];if(be([0,a[2]],[0,d]))throw j(v,1);a=l(e,b);return[0,[13,c,d,a[1]],a[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){d=b[1];b=b[3];c=a[3];e=a[2];a=a[1];var
f=[0,o(d)];if(be([0,o(e)],f))throw j(v,1);b=l(c,o(b));return[0,[14,a,d,b[1]],b[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){b=l(a[1],b[1]);return[0,[15,b[1]],b[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){b=l(a[1],b[1]);return[0,[16,b[1]],b[2]]}break;case
17:d=a[1];b=l(a[2],b);return[0,[17,d,b[1]],b[2]];case
18:d=a[2];a=a[1];if(0===a[0]){a=a[1];c=a[2];b=l(a[1],b);a=b[1];b=l(d,b[2]);return[0,[18,[0,[0,a,c]],b[1]],b[2]]}a=a[1];c=a[2];a=l(a[1],b);b=a[1];a=l(d,a[2]);return[0,[18,[1,[0,b,c]],a[1]],a[2]];case
19:if(typeof
b!=="number"&&13===b[0]){a=l(a[1],b[1]);return[0,[19,a[1]],a[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){c=a[2];d=a[1];a=l(a[3],b[1]);return[0,[20,d,c,a[1]],a[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){c=a[1];a=l(a[2],b[1]);return[0,[21,c,a[1]],a[2]]}break;case
23:c=a[2];a=a[1];if(typeof
a!=="number")switch(a[0]){case
8:return b6([8,a[1],a[2]],c,b);case
9:d=a[1];b=F(a[2],c,b);a=b[2];return[0,[23,[9,d,b[1]],a[1]],a[2]];default:return b6(a,c,b)}if(2!==a)return b6(a,c,b);if(typeof
b!=="number"&&14===b[0]){c=l(c,b[1]);return[0,[23,2,c[1]],c[2]]}throw j(v,1)}throw j(v,1)}function
b6(a,b,c){b=l(b,c);return[0,[23,a,b[1]],b[2]]}function
F(a,b,c){if(typeof
a==="number")return[0,0,l(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){b=F(a[1],b,c[1]);return[0,[0,b[1]],b[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){a=F(a[1],b,c[1]);return[0,[1,a[1]],a[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){b=F(a[1],b,c[1]);return[0,[2,b[1]],b[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){b=F(a[1],b,c[1]);return[0,[3,b[1]],b[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){b=F(a[1],b,c[1]);return[0,[4,b[1]],b[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){b=F(a[1],b,c[1]);return[0,[5,b[1]],b[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){c=F(a[1],b,c[1]);return[0,[6,c[1]],c[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){b=F(a[1],b,c[1]);return[0,[7,b[1]],b[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
d=c[1],c=c[2],e=a[2];if(be([0,a[1]],[0,d]))throw j(v,1);c=F(e,b,c);return[0,[8,d,c[1]],c[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){d=c[2];e=c[1];c=c[3];var
g=a[3],f=a[2],a=a[1],h=[0,o(e)];if(be([0,o(a)],h))throw j(v,1);a=[0,o(d)];if(be([0,o(f)],a))throw j(v,1);a=x(t(r(e),d));f=a[4];a[2].call(null,0);f(0);a=F(o(g),b,c);c=a[2];return[0,[9,e,d,r(a[1])],c]}break;case
10:if(typeof
c!=="number"&&10===c[0]){a=F(a[1],b,c[1]);return[0,[10,a[1]],a[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){a=F(a[1],b,c[1]);return[0,[11,a[1]],a[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){c=F(a[1],b,c[1]);return[0,[13,c[1]],c[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){b=F(a[1],b,c[1]);return[0,[14,b[1]],b[2]]}break}throw j(v,1)}var
eK=120;function
H(a,b,c){var
d=E(c),a=0<=b?a:0,b=bg(b);if(b<=d)return c;var
e=2===a?48:32,e=au(b,e);switch(a){case
0:Y(c,0,e,0,d);break;case
1:Y(c,0,e,b-d|0,d);break;default:a:if(0<d){if(43!==J(c,0)&&45!==J(c,0)&&32!==J(c,0))break a;aC(e,0,J(c,0));Y(c,1,e,(b-d|0)+1|0,d-1|0);break}a:if(1<d&&48===J(c,0)){if(eK!==J(c,1)&&88!==J(c,1))break a;aC(e,1,J(c,1));Y(c,2,e,(b-d|0)+2|0,d-2|0);break}Y(c,0,e,b-d|0,d)}return L(e)}var
ec=-97;function
aJ(a,b){a=bg(a);var
d=E(b),c=J(b,0);a:{b:{if(58>c){if(32!==c){if(43>c)break a;switch(c-43|0){case
5:if(d>=(a+2|0))break b;if(1>=d)break b;if(eK!==J(b,1)&&88!==J(b,1))break b;c=au(a+2|0,48);aC(c,1,J(b,1));Y(b,2,c,(a-d|0)+4|0,d-2|0);return L(c);case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(d>=(a+1|0))break a;var
e=au(a+1|0,48);aC(e,0,c);Y(b,1,e,(a-d|0)+2|0,d-1|0);return L(e)}if(71<=c){if(5<c+ec>>>0)break a}else if(65>c)break a}if(d<a){e=au(a,48);Y(b,0,e,a-d|0,d);return L(e)}}return b}function
fQ(a){var
g=aB(a),f=X(g)-1|0,d=0;if(f<0);else{var
e=0;for(;;){var
b=cY(g,e);a:{b:{c:{if(32<=b){b=b-34|0;if(58<b>>>0){if(93<=b)break c}else if(56<b-1>>>0)break b;b=1;break a}if(11<=b){if(13===b)break b}else if(8<=b)break b}b=4;break a}b=2}d=d+b|0;b=e+1|0;if(f===e)break;e=b}}if(d===X(g))d=g;else{d=z(d);f=X(g)-1|0;if(f<0);else{b=0;e=0;for(;;){var
c=cY(g,e);a:{b:{c:{if(35<=c){if(92!==c){if(cH<=c)break b;break c}}else{if(32>c){if(14<=c)break b;switch(c){case
8:q(d,b,92);c=b+1|0;q(d,c,98);break a;case
9:q(d,b,92);c=b+1|0;q(d,c,116);break a;case
10:q(d,b,92);c=b+1|0;q(d,c,110);break a;case
13:q(d,b,92);c=b+1|0;q(d,c,114);break a;default:break b}}if(34>c)break c}q(d,b,92);b=b+1|0;q(d,b,c);c=b;break a}q(d,b,c);c=b;break a}q(d,b,92);b=b+1|0;q(d,b,48+(c/bz|0)|0);b=b+1|0;q(d,b,48+((c/10|0)%10|0)|0);b=b+1|0;q(d,b,48+(c%10|0)|0);c=b}b=c+1|0;c=e+1|0;if(f===e)break;e=c}}}c=g===d?a:L(d);f=E(c);a=au(f+2|0,34);bI(c,0,a,1,f);return L(a)}var
eu=103,fR=[0,eu];function
dz(a,b){b=bg(b);var
c=fR[1];switch(a[2]){case
0:c=102;break;case
1:c=101;break;case
2:c=69;break;case
3:c=eu;break;case
4:c=71;break;case
6:c=104;break;case
7:c=72;break;case
8:c=70;break}var
d=dv(16);aI(d,37);switch(a[1]){case
1:aI(d,43);break;case
2:aI(d,32);break}if(8<=a[2])aI(d,35);aI(d,46);w(d,e+b);aI(d,c);return dx(d)}function
bj(a,b){if(13>a)return b;a=E(b)-1|0;var
i=-48,c=0;if(a<0);else{var
d=0;for(;;){c=9<bU(b,d)+i>>>0?c:c+1|0;var
e=d+1|0;if(a===d)break;d=e}}var
g=z(E(b)+((c-1|0)/3|0)|0),h=[0,0];function
f(a){aC(g,h[1],a);h[1]++}var
a=E(b)-1|0,c=((c-1|0)%3|0)+1|0;if(a>=0){e=0;for(;;){d=bU(b,e);if(9<d+i>>>0)f(d);else{c=0===c?(f(95),3):c;f(d);c=c-1|0}d=e+1|0;if(a===e)break;e=d}}return L(g)}var
eP="%u";function
fS(a,b){switch(a){case
1:var
c="%+d";break;case
2:c="% d";break;case
4:c="%+i";break;case
5:c="% i";break;case
6:c="%x";break;case
7:c="%#x";break;case
8:c="%X";break;case
9:c="%#X";break;case
10:c="%o";break;case
11:c="%#o";break;case
0:case
13:c=cN;break;case
3:case
14:c=d_;break;default:c=eP}return bj(a,bN(c,b))}function
fT(a,b){switch(a){case
1:var
c="%+ld";break;case
2:c="% ld";break;case
4:c="%+li";break;case
5:c="% li";break;case
6:c="%lx";break;case
7:c="%#lx";break;case
8:c="%lX";break;case
9:c="%#lX";break;case
10:c="%lo";break;case
11:c="%#lo";break;case
0:case
13:c="%ld";break;case
3:case
14:c=eg;break;default:c="%lu"}return bj(a,bN(c,b))}function
fU(a,b){switch(a){case
1:var
c="%+nd";break;case
2:c="% nd";break;case
4:c="%+ni";break;case
5:c="% ni";break;case
6:c="%nx";break;case
7:c="%#nx";break;case
8:c="%nX";break;case
9:c="%#nX";break;case
10:c="%no";break;case
11:c="%#no";break;case
0:case
13:c="%nd";break;case
3:case
14:c=eU;break;default:c="%nu"}return bj(a,bN(c,b))}function
fV(a,b){switch(a){case
1:var
c="%+Ld";break;case
2:c="% Ld";break;case
4:c="%+Li";break;case
5:c="% Li";break;case
6:c="%Lx";break;case
7:c="%#Lx";break;case
8:c="%LX";break;case
9:c="%#LX";break;case
10:c="%Lo";break;case
11:c="%#Lo";break;case
0:case
13:c="%Ld";break;case
3:case
14:c=er;break;default:c="%Lu"}return bj(a,hj(c,b))}function
aa(h,b,c){function
i(a){switch(h[1]){case
0:a=45;break;case
1:a=43;break;default:a=32}return he(c,b,a)}function
j(a){var
b=g6(c);return 3===b?c<0.?"neg_infinity":eF:4<=b?cV:a}switch(h[2]){case
5:var
a=c1(dz(h,b),c),f=0,d=E(a);for(;;){a:{if(f!==d){var
e=J(a,f)-46|0;b:{if(23<e>>>0){if(55!==e)break b}else if(21>=e-1>>>0)break b;d=1;break a}f=f+1|0;continue}d=0}a=d?a:a+af;return j(a)}case
6:return i(0);case
7:a=aB(i(0));d=X(a);if(0===d);else{f=z(d);d=d-1|0;if(d<0)a=f;else{e=0;for(;;){var
g=cY(a,e),g=25<g+ec>>>0?g:g-32|0;q(f,e,g);g=e+1|0;if(d===e){a=f;break}e=g}}}return L(a);case
8:return j(i(0));default:return c1(dz(h,b),c)}}var
fX=[0,a,1558,4],fY=[0,a,1626,39];function
a5(a,b,c,d){var
i=0;a:for(;;)switch(i){case
0:var
g=b,f=c,e=d;b:for(;;){if(typeof
e==="number")return m(g,f);switch(e[0]){case
0:i=1;continue a;case
1:i=2;continue a;case
2:i=3;continue a;case
3:return b7(g,f,e[2],e[1],fQ);case
4:return bk(g,f,e[4],e[2],e[3],fS,e[1]);case
5:return bk(g,f,e[4],e[2],e[3],fT,e[1]);case
6:return bk(g,f,e[4],e[2],e[3],fU,e[1]);case
7:return bk(g,f,e[4],e[2],e[3],fV,e[1]);case
8:i=4;continue a;case
9:return b7(g,f,e[2],e[1],fy);case
10:f=[7,f];e=e[1];break;case
11:f=[2,f,e[1]];e=e[2];break;case
12:f=[3,f,e[1]];e=e[2];break;case
13:i=5;continue a;case
14:i=6;continue a;case
15:i=7;continue a;case
16:i=8;continue a;case
17:f=[0,f,e[1]];e=e[2];break;case
18:i=e[1];if(0===i[0]){let
b=f,c=g,d=e[2];g=function(a){return h(c,[1,b,[0,a]],d)};f=0;e=i[1][1]}else{let
b=f,c=g,d=e[2];g=function(a){return h(c,[1,b,[1,a]],d)};f=0;e=i[1][1]}break;case
19:throw j([0,p,fX],1);case
20:i=9;continue a;case
21:i=10;continue a;case
22:i=11;continue a;case
23:break b;default:i=e[3];b=e[1];d=m(e[2],0);return a<50?cy(a+1|0,g,f,i,b,d):aF(cy,[0,g,f,i,b,d])}}case
12:c=e[2];d=e[1];if(typeof
d==="number"){if(2===d)throw j([0,p,fY],1);return a<50?aN(a+1|0,g,f,c):aF(aN,[0,g,f,c])}if(9!==d[0])return a<50?aN(a+1|0,g,f,c):aF(aN,[0,g,f,c]);b=d[2];return a<50?cz(a+1|0,g,f,b,c):aF(cz,[0,g,f,b,c]);case
11:var
N=e[1];return function(a){return h(g,[5,f,a],N)};case
10:var
M=e[2];return function(a){return h(g,[4,f,bN(eP,a)],M)};case
9:var
J=e[3],K=[8,f,"Printf: bad conversion %["];return function(a){return h(g,K,J)};case
8:var
I=e[1];return function(a){return h(g,[6,f,a],I)};case
7:var
G=e[1];return function(c,b){return h(g,[6,f,function(a){return B(c,a,b)}],G)};case
6:var
D=e[3],F=e[2];return function(a){a=a[1];a=l(a,o(r(F)));if(typeof
a[2]==="number")return h(g,f,n(a[1],D));throw j(v,1)};case
5:var
C=e[3],i=e[2],e=dv(16);b5(e,i);var
x=dx(e);return function(a){return h(g,[4,f,x],C)};case
4:var
s=e[4],i=e[3],b=e[2],k=e[1];if(typeof
b==="number"){if(typeof
i==="number")return i?function(a,b){return h(g,[4,f,aa(k,a,b)],s)}:function(a){return h(g,[4,f,aa(k,b4(k),a)],s)};var
O=i[1];return function(a){return h(g,[4,f,aa(k,O,a)],s)}}if(0===b[0]){var
t=b[2],u=b[1];if(typeof
i==="number")return i?function(a,b){return h(g,[4,f,H(u,t,aa(k,a,b))],s)}:function(a){return h(g,[4,f,H(u,t,aa(k,b4(k),a))],s)};var
P=i[1];return function(a){return h(g,[4,f,H(u,t,aa(k,P,a))],s)}}var
w=b[1];if(typeof
i==="number")return i?function(a,b,c){return h(g,[4,f,H(w,a,aa(k,b,c))],s)}:function(a,b){return h(g,[4,f,H(w,a,aa(k,b4(k),b))],s)};var
Q=i[1];return function(a,b){return h(g,[4,f,H(w,a,aa(k,Q,b))],s)};case
3:return b7(g,f,e[2],e[1],function(a){return a});case
2:var
A=e[1];return function(a){a:{b:{if(40<=a){if(92===a){a="\\\\";break a}if(cH<=a)break b}else{if(32>a){if(14<=a)break b;switch(a){case
8:a="\\b";break a;case
9:a="\\t";break a;case
10:a="\\n";break a;case
13:a="\\r";break a;default:break b}}if(39<=a){a="\\'";break a}}var
b=z(1);q(b,0,a);a=L(b);break a}b=z(4);q(b,0,92);q(b,1,48+(a/bz|0)|0);q(b,2,48+((a/10|0)%10|0)|0);q(b,3,48+(a%10|0)|0);a=L(b)}b=E(a);var
c=au(b+2|0,39);bI(a,0,c,1,b);return h(g,[4,f,L(c)],A)};case
1:var
y=e[1];return function(a){return h(g,[5,f,a],y)}}}function
h(a,b,c){return dc(a5(0,a,b,c))}var
fZ=[0,a,1649,31],f0=[0,a,1650,31];function
cz(a,f,c,d,e){if(typeof
d==="number")return a<50?aN(a+1|0,f,c,e):aF(aN,[0,f,c,e]);switch(d[0]){case
0:var
b=d[1];return function(a){return K(f,c,b,e)};case
1:var
g=d[1];return function(a){return K(f,c,g,e)};case
2:var
h=d[1];return function(a){return K(f,c,h,e)};case
3:var
i=d[1];return function(a){return K(f,c,i,e)};case
4:var
k=d[1];return function(a){return K(f,c,k,e)};case
5:var
l=d[1];return function(a){return K(f,c,l,e)};case
6:var
m=d[1];return function(a){return K(f,c,m,e)};case
7:var
n=d[1];return function(a){return K(f,c,n,e)};case
8:var
o=d[2];return function(a){return K(f,c,o,e)};case
9:var
q=d[3],a=d[2],s=t(r(d[1]),a);return function(a){return K(f,c,A(s,q),e)};case
10:var
u=d[1];return function(a,b){return K(f,c,u,e)};case
11:var
v=d[1];return function(a){return K(f,c,v,e)};case
12:var
w=d[1];return function(a){return K(f,c,w,e)};case
13:throw j([0,p,fZ],1);default:throw j([0,p,f0],1)}}function
K(a,b,c,d){return dc(cz(0,a,b,c,d))}function
aN(a,b,c,d){c=[8,c,"Printf: bad conversion %_"];return a<50?a5(a+1|0,b,c,d):aF(a5,[0,b,c,d])}function
b7(g,f,c,d,e){if(typeof
d==="number")return function(a){return h(g,[4,f,m(e,a)],c)};if(0===d[0]){var
b=d[2],i=d[1];return function(a){return h(g,[4,f,H(i,b,m(e,a))],c)}}var
j=d[1];return function(a,b){return h(g,[4,f,H(j,a,m(e,b))],c)}}function
bk(k,j,i,d,e,f,g){if(typeof
d==="number"){if(typeof
e==="number")return e?function(a,b){return h(k,[4,j,aJ(a,B(f,g,b))],i)}:function(a){return h(k,[4,j,B(f,g,a)],i)};var
b=e[1];return function(a){return h(k,[4,j,aJ(b,B(f,g,a))],i)}}if(0===d[0]){var
c=d[2],l=d[1];if(typeof
e==="number")return e?function(a,b){return h(k,[4,j,H(l,c,aJ(a,B(f,g,b)))],i)}:function(a){return h(k,[4,j,H(l,c,B(f,g,a))],i)};var
n=e[1];return function(a){return h(k,[4,j,H(l,c,aJ(n,B(f,g,a)))],i)}}var
m=d[1];if(typeof
e==="number")return e?function(a,b,c){return h(k,[4,j,H(m,a,aJ(b,B(f,g,c)))],i)}:function(a,b){return h(k,[4,j,H(m,a,B(f,g,b))],i)};var
o=e[1];return function(a,b){return h(k,[4,j,H(m,a,aJ(o,B(f,g,b)))],i)}}function
cy(a,b,c,d,e,f){if(e){var
g=e[1];return function(a){return fW(b,c,d,g,m(f,a))}}e=[4,c,f];return a<50?a5(a+1|0,b,e,d):aF(a5,[0,b,e,d])}function
fW(a,b,c,d,e){return dc(cy(0,a,b,c,d,e))}var
ey="@{",eI="@[";function
ab(a,b){for(;;){if(typeof
b==="number")return;switch(b[0]){case
0:var
c=b[1],b=dy(b[2]);ab(a,c);return aX(a,b);case
1:c=b[2];b=b[1];if(0===c[0]){c=c[1];ab(a,b);aX(a,ey);b=c}else{c=c[1];ab(a,b);aX(a,eI);b=c}break;case
6:c=b[2];ab(a,b[1]);return m(c,a);case
7:ab(a,b[1]);ai(a);return;case
8:c=b[2];ab(a,b[1]);return ak(c);case
2:case
4:c=b[2];ab(a,b[1]);return aX(a,c);default:c=b[2];ab(a,b[1]);fj(a,c);return}}}function
al(a,b){for(;;){if(typeof
b==="number")return;switch(b[0]){case
0:var
c=b[1],b=dy(b[2]);al(a,c);return aZ(a,b);case
1:c=b[2];b=b[1];if(0===c[0]){c=c[1];al(a,b);aZ(a,ey);b=c}else{c=c[1];al(a,b);aZ(a,eI);b=c}break;case
6:c=b[2];al(a,b[1]);return aZ(a,m(c,0));case
7:b=b[1];break;case
8:c=b[2];al(a,b[1]);return ak(c);case
2:case
4:c=b[2];al(a,b[1]);return aZ(a,c);default:c=b[2];al(a,b[1]);var
d=a[2],e=a[1],f=e[1];if(e[2]<=d){du(a,1);aC(a[1][1],a[2],c)}else
q(f,d,c);a[2]=d+1|0;return}}}function
bl(c,b){return h(function(a){ab(c,a);return 0},0,b[1])}function
N(a){return h(function(a){var
c=aY<64?aY:64,b=z(c),b=[0,[0,b,c],0,b];al(b,a);return ds(b[1][1],0,b[2])},0,a[1])}var
f1=[0,[3,0,0],"%S"],f2=[0,[4,0,0,0,0],cN];function
b9(a,b){a=a[b+1];if(!(1-(typeof
a==="number")))return m(N(f2),a);if(bS(a)===bw)return m(N(f1),a);if(bS(a)!==253)return el;a=c1("%.12g",a);b=0;var
d=E(a);for(;;){if(d<=b)return a+af;var
c=J(a,b);a:{if(48<=c){if(58<=c)break a}else if(45!==c)break a;b=b+1|0;continue}return a}}var
f3=[0,[11,cC,[2,0,[2,0,0]]],", %s%s"];function
dA(a,b){if(a.length-1<=b)return e;var
c=dA(a,b+1|0),b=b9(a,b);return B(N(f3),b,c)}var
a=", characters ",b8=[0,[11,'File "',[2,0,[11,'", line ',[4,0,0,0,[11,a,[4,0,0,0,[12,45,[4,0,0,0,[11,a$,[2,0,0]]]]]]]]]],'File "%s", line %d, characters %d-%d: %s'],b1=[0,0],f4=[0,[12,40,[2,0,[2,0,[12,41,0]]]],"(%s%s)"],f5=[0,[12,40,[2,0,[12,41,0]]],"(%s)"];function
bm(a){a:{b:{var
d=b1[1];for(;;){if(!d)break;var
c=d[2],d=d[1];try{var
b=m(d,a)}catch(f){d=c;continue}if(b)break b;d=c}d=0;break a}d=[0,b[1]]}if(d)return d[1];if(a===bZ)return"Out of memory";if(a===dn)return"Stack overflow";if(a[1]===dm){a=a[2];b=a[3];c=a[2];a=a[1];return cA(N(b8),a,c,b,b+5|0,"Pattern matching failed")}if(a[1]===p){a=a[2];c=a[3];b=a[2];a=a[1];return cA(N(b8),a,b,c,c+6|0,"Assertion failed")}if(a[1]===dq){a=a[2];b=a[3];c=a[2];a=a[1];return cA(N(b8),a,c,b,b+6|0,"Undefined recursive module")}if(0===bS(a)){b=a.length-1;c=a[1][1];if(2<b>>>0){b=dA(a,2);a=b9(a,1);a=B(N(f4),a,b)}else
switch(b){case
2:a=b9(a,1);a=m(N(f5),a);break;case
0:a=e;break;default:a=e}a=[0,c,[0,a]]}else
a=[0,a[1],0];b=a[2];c=a[1];return b?c+b[1]:c}var
f6=[0,[12,32,[4,0,0,0,0]]," %d"],f7=[0,[2,0,[12,32,[2,0,[11,' in file "',[2,0,[12,34,[2,0,[11,", line",[2,0,[11,a,[4,0,0,0,[12,45,[4,0,0,0,0]]]]]]]]]]]]],'%s %s in file "%s"%s, line%s, characters %d-%d'],f8=[0,[11,"s ",[4,0,0,0,[12,45,[4,0,0,0,0]]]],"s %d-%d"],f9=[0,[2,0,[11," unknown location",0]],"%s unknown location"],f_=[0,[2,0,[12,10,0]],"%s\n"];function
b_(a,b){b=g7(b);var
i=b.length-2|0;if(i>=0){var
f=0;for(;;){var
c=e8(b,f)[f+1];let
j=f;var
h=function(a){return a?0===j?"Raised at":"Re-raised at":0===j?"Raised by primitive operation at":"Called from"};if(0===c[0]){if(c[3]===c[6])var
d=c[3],d=m(N(f6),d);else{d=c[6];var
g=c[3],d=B(N(f8),g,d)}g=c[7];var
k=c[4],l=c[8]?" (inlined)":e,n=c[2],o=c[9],c=h(c[1]),c=[0,gT(N(f7),c,o,n,l,d,k,g)]}else if(c[1])c=0;else{c=h(0);c=[0,m(N(f9),c)]}if(c){c=c[1];m(bl(a,f_),c)}c=f+1|0;if(i===f)break;f=c}}}var
f$=hI([0,e,"(Cannot print locations:\n bytecode executable program file not found)","(Cannot print locations:\n bytecode executable program file appears to be corrupt)","(Cannot print locations:\n bytecode executable program file has wrong magic number)","(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)"]),a="Fatal error: exception %s\n",ga=[0,[11,cO,[2,0,[12,10,0]]],a],gb=[0],gc=[0,[11,cO,[2,0,[12,10,0]]],a],gd=[0,[11,"Fatal error in uncaught exception handler: exception ",[2,0,[12,10,0]]],"Fatal error in uncaught exception handler: exception %s\n"];db(eb,function(a,b){try{try{var
d=b?gb:fd(0);try{b0(0)}catch(f){}try{var
c=bm(a);m(bl(T,ga),c);b_(T,d);c=hC(0);if(c<0){c=bg(c);dr(e8(f$,c)[c+1])}c=ai(T)}catch(f){c=aG(f);a=bm(a);m(bl(T,gc),a);b_(T,d);c=bm(c);m(bl(T,gd),c);b_(T,fd(0));c=ai(T)}d=c}catch(f){d=aG(f);if(d!==bZ)throw j(d,0);d=dr("Fatal error: out of memory in uncaught exception handler")}return d}catch(f){return 0}});var
ge=[u,"Stdlib.Fun.Finally_raised",c2(0)];(function(a){for(;;){var
b=b1[1],b=1-gZ(b1,0,b,[0,a,b]);if(!b)return b}}(function(a){return a[1]===ge?[0,"Fun.Finally_raised: "+bm(a[2])]:0}));var
a1=[u,"Jsoo_runtime.Error.Exn",c2(0)];function
fz(a,b){return[0,a,b]}var
a=[0,a1,[0]],a=bS(a)===u?a:a[1];db(cT,a);function
dB(a,b){a=a?a[1]:10;return b.toString(a)}function
b$(a,b){if(a.length<=b){a=dB(0,a.length-1|0);return ak(M("index ".concat(dB(0,b)).concat(" not in bounds [0;").concat(a).concat("]")))}b=a.codePointAt(b);b=55296<=b?57343<b?b:65533:b;return b}function
ca(a,b,c){a=a?a[1]:0;a=c.indexOf(b,a);return-1===a?0:[0,a]}function
Z(a,b,c){a=a?a[1]:0;a=b?[0,a,b[1]]:[0,a];return fg(c,"slice",a)}function
cb(a,b){return hy(b.split(a))}function
I(a){return 0===a.length?1:0}var
aL=null,av=undefined;function
aw(a){var
b=a===aL?1:0;return b?b:a===av?1:0}var
i=c;function
bn(a,b,c){if(!c)return;a[b]=!!c[1]}function
am(a,b,c){if(!c)return;a[b]=c[1]}function
dD(a,b){b=new
i.Error(b);return a?(b.name=a[1],b):b}function
cd(a,b){return m(function(a){throw a},dD(a,b))}function
bo(a){a=a.done;a=aw(a)?0:[0,a|0];return a?a[1]:0}var
bp=i.Promise;function
dE(a){return new
bp(ah(2,function(c,b){return B(a,function(a){return c(a)},function(a){return b(a)})}))}function
_(a){return{fut:bp.resolve(a)}}function
ax(a,b){return{fut:a.fut.then(ah(1,function(a){return m(b,a).fut}))}}function
dF(c){return{fut:dE(function(a,b){i.setTimeout(ah(1,a),c);return 0})}}function
dG(c,b){return{fut:b.then(ah(1,function(a){return bp.resolve([0,m(c,a)])}),ah(1,function(a){return bp.resolve([1,a])}))}}var
gh=i.Event;function
ce(a,b){a=a?a[1]:{};return new
gh(b,a)}function
dH(a){a.preventDefault()}function
cf(a,b){return b.dispatchEvent(a)|0}function
cg(a,b,c,d){a=a?a[1]:{};d.addEventListener(b,ah(1,c),a)}i.ArrayBuffer;i.DataView;i.Blob;i.File;i.JSON;i.encodeURI;i.encodeURIComponent;i.decodeURIComponent;var
ch=i.URL,gk=[0,-1];function
dI(a){a=a.protocol;return 0===a.length?a:Z(0,gk,a)}function
ci(a,b){try{var
c=a?new
ch(b,a[1]):new
ch(b)}catch(f){c=aG(f);if(c[1]===a1)return[1,c[2]];throw j(c,0)}return[0,c]}i.RegExp;var
an=i.document,gf=c.Number,gj=i.decodeURI,gm=i.URLSearchParams,gn=aw(an)?av:an.documentElement;function
dJ(a){var
b=a.length-1|0,c=0;if(b<0);else
for(;;){c=[0,a[b],c];var
d=b-1|0;if(0===b)break;b=d}return c}function
cj(a){return 1===a.nodeType?1:0}function
a2(a){return a.nodeName.toLowerCase()}function
ck(a,b,c,d){a=a?a[1]:gn;c=a.querySelectorAll(c);a=c.length-1|0;if(a<0);else{var
e=0;for(;;){d=B(b,c[e],d);var
f=e+1|0;if(a===e)break;e=f}}return d}function
a3(a){a=a.parentNode;a=aw(a)?0:[0,a];if(a){a=a[1];if(cj(a))return[0,a]}return 0}function
bq(a,b){a=a?a[1]:0;return a?dJ(b.children):dJ(b.childNodes)}function
ac(a,b){a=b.getAttribute(a);return aw(a)?0:[0,a]}var
aK=e;function
go(a){return a===av?aK:a}function
cl(a){return[0,a,go,function(a){return a}]}var
gp=cl("name");function
cm(a,b){b=b[a[1]];return m(a[2],b)}function
dK(a,b,c){b=m(a[3],b);c[a[1]]=b}function
ad(a,b,c){if(b){c.classList.add(a);return}c.classList.remove(a)}var
en="value",gq=cl(en);i["Range.END_TO_END"];i["Range.END_TO_START"];i["Range.START_TO_END"];i["Range.START_TO_START"];i.Range;function
dL(a){return new
ch(a.location)}i.console;i.navigator;i.performance;var
aM=i.window;i.isSecureContext;function
dM(a,b){return i.setTimeout(ah(1,b),a)}function
dN(a){i.requestAnimationFrame(ah(1,a))}i.ClipboardItem;var
cn=i.FormData;function
co(a,b,c){a.append(b,c)}function
cp(a){return new
i.URLSearchParams(a)}var
gv=i.Headers;function
br(a,b){a=b.get(a);return aw(a)?0:[0,a]}function
dO(a,b,c,d,e,f,g,h,i,j,k,l,m){a=a?a[1]:av;m={};m.body=a;am(m,"cache",b);am(m,"credentials",c);d=d?[0,d[1]]:0;if(d)m.headers=d[1];am(m,"integrity",e);bn(m,"keepalive",f);am(m,"method",g);am(m,"mode",h);am(m,"redirect",i);am(m,"referrer",j);am(m,"referrerPolicy",k);l=l?l[1]:av;m.signal=l;return m}var
gw=i.Request;function
dP(a,b){a=a?a[1]:{};return new
gw(b,a)}i.Response;i.MediaStream;i.MediaRecorder;i.MessageChannel;i.BroadcastChannel;i.Notification;i.WebSocket;var
dQ=i.MutationObserver;function
dR(a,b,c){a.observe(b,c)}i.IntersectionObserver;var
gr=i.console;function
cq(a){cf(ce(0,a),an)}function
O(a){return[1,dD(0,a)]}function
a4(a,b){if(0===b[0])return b[1];b=b[1];cq("htmlact-cycle-error");a=[0,a,[0,b,0]];b="htmlact: element ";var
c=b,c=c===aL?"null":c===av?"undefined":b.toString(),b=new
i.Array(0),d=0,a=[0,c,a];for(;;){if(!a){fg(gr,eo,hx(b));return 0}c=a[2];b[d]=a[1];d=d+1|0;a=c}}var
dC=V;function
dU(a){return cb(dC,a.trim())}function
ae(a){return cd(0,a)}function
dV(a,b){for(;;){if(!b)return[0,a];var
f=b[1],b=b[2];a:for(;;){var
d=f[1],c=f[2],a=a3(a);if(a){a=a[1];var
e=I(d),e=e||k(d,a2(a));for(;;){if(c){d=c[2];c=a.classList.contains(c[1])|0;if(c){c=d;continue}}else
c=1;if(!e)continue a;if(c){a=[0,a];break}continue a}}else
a=0;if(!a)return 0;a=a[1];break}}}function
dW(a,b,c,d){var
e=b[2],a=dV(a,b[1]);if(!a)return d;a=a[1];return I(e)?B(c,a,d):ck([0,a],c,e,d)}function
cs(a){var
d=0,c=0;for(;;){var
b=ca([0,c],":up",a);a:if(b){b=b[1];var
e=b+3|0;if(e!==a.length&&32!==b$(a,e)){b=0;break a}b=[0,b]}else
b=0;if(!b){b=Z([0,c],0,a).trim();b=I(b)?b:hz([0,":scope",[0,b,0]]).join(V);return[0,b3(d),b]}b=b[1];c=cb(af,Z([0,c],[0,b],a).trim());d=c?[0,[0,c[1],c[2]],d]:[0,[0,aK,0],d];c=b+3|0}}function
dX(a){var
b=a.length;if(2>b)return 0;b=b-1|0;if(115!==b$(a,b))return 0;if(109===b$(a,b-1|0)){b=b-1|0;var
c=1.}else
c=1000.;a=gf.parseFloat(Z(0,[0,b],a));if(a===a&&!(a<0.))return[0,a*c|0];return 0}var
ef="key ";function
dY(a,b){var
c=dX(b);return c?c[1]:ae(ef.concat(a).concat(": invalid duration: ").concat(b))}var
cB="form";function
dZ(a,b){if(!k(a2(a),cB)){var
c=cm(gq,a);if(I(c))return b;a=cm(gp,a);a=I(a)?en:a;co(b,a,c);return b}a=k(cB,a2(a))?a:cd(0,"Expected form element but found: ".concat(a2(a)));a=new
cn(a);if(bo(b.entries().next()))return a;a=a.entries();for(;;){c=a.next();if(bo(c))return b;c=c.value;var
d=c[1],e=781515420,f=d
instanceof
i.File?[0,e]:[0,-976970511],c=c[0];if(e<=f[1])b.append(c,d,av);else
co(b,c,d)}}var
gl=[0,1];function
d0(a,b){if(a){a=a[1].search;a=I(a)?a:Z(gl,0,a);a=new
gm(a);var
d=new
cn,a=a.entries();for(;;){var
c=a.next();if(bo(c))break;c=c.value;var
e=c[1];co(d,c[0],e)}}else
d=new
cn;a=ac("data-query",b);return a?dW(b,cs(a[1]),dZ,d):dZ(b,d)}var
gx=i.fetch,ct=cl("data-htmlact-rescue-stamp");function
d1(a){return cp(d0(0,a)).toString()}var
bE="data-query-rescue",ep=": invalid value: ";function
d2(a){var
c=bE,b=ac(c,a);if(!b)return;b=b[1];if(k(cD,b))return;var
d=d1(a);if(k(a9,b))return dK(ct,d,a);if(!k("force",b))return a4(a,[1,bE.concat(ep).concat(b)]);dK(ct,"Force!".concat(d),a);if(I(c))return;a.setAttribute(bE,a9)}var
eS="missing event name",ew="once",ed="submit",gy=[0,-1];function
gz(a){var
h="data-event",d=ac(h,a);if(!d){var
c=a2(a),d="change",d=k(c,cB)?ed:k(c,"input")?d:k(c,"textarea")?d:k(c,"select")?d:"click";return[0,[0,[0,d,0,0,0,0],0]]}a=0;d=cb(ei,d[1]);for(;;){if(d){var
n=d[2],d=d[1];try{c=dU(d);if(c){d=c[2];c=[0,c[1].trim(),d]}else
c=ae(eS);d=0;var
g=0,l=0,i=0,b=c[2],c=c[1];for(;;){if(b){var
f=b[2],e=b[1].trim();if(I(e)){b=f;continue}a:{if(k(e,ew)){d=1;b=f;continue}for(;;){if(!b){b=0;break a}f=b[2];b=b[1].trim();if(!I(b))break;b=f}e=ca(0,es,b);if(e){e=e[1];if(e===(b.length-1|0))if(f){e=f[2];f=f[1].trim();b=[0,[0,Z(0,gy,b.trim()),f,e]]}else
b=ae(ef.concat(b).concat(": missing value"));else
var
m=Z([0,e+1|0],0,b),b=[0,[0,Z(0,[0,e],b),m,f]]}else
b=ae("not a key: ".concat(b))}if(b){b=b[1];f=b[3];e=b[2];b=b[1];if(k(b,"debounce")){g=dY(b,e);b=f;continue}if(k(b,"throttle")){l=dY(b,e);b=f;continue}if(k(b,"filter")){i=[0,e];b=f;continue}g=ae("unknown key: ".concat(b))}else
g=[0,d,g,l,i]}else
g=[0,d,g,l,i];c=[0,[0,c,g[1],g[2],g[3],g[4]]];break}}catch(f){c=aG(f);if(c[1]!==a1)throw j(c,0);c=O("event: ".concat(c[2].message))}if(0===c[0]){a=[0,c[1],a];d=n;continue}}else
c=[0,b3(a)];if(0===c[0])return c;a=c[1];h=h.concat(a$);return O(h.concat(a.message))}}function
bs(a,b){a=a[5];return a?i[a[1]](b)|0:1}function
bt(a){if(k(a.type,ed))return dH(a)}var
gg=[0,"src/fut.ml",34,25],gi=[0,1],gA=[0,0];function
d3(e,b,c){d2(b);c=gz(b);if(0===c[0]){c=c[1];for(;;){if(!c){c=gA;break}var
h=c[2],c=c[1];if(c[2]){let
f=c;var
a=[0,function(a){throw j([0,p,gg],1)}];let
g=a;c=c[1];let
i=function(a){return cd(0,"The future is already set")};a={fut:dE(function(a,b){g[1]=a;return 0})};var
d={};bn(d,"capture",0);bn(d,ew,gi);bn(d,"passive",0);cg([0,d],c,function(a){m(g[1],a);g[1]=i;return 0},b);ax(a,function(b){bt(b);return bs(f,b)?0<f[3]?ax(dF(f[3]),function(a){return _(m(e,b))}):_(m(e,b)):_(0)});c=h}else{a=c[1];if(0===c[3])if(0===c[4]){let
b=c;var
f=function(a){bt(a);return bs(b,a)?m(e,a):0}}else{let
b=[0,0],d=c;f=function(a){bt(a);return bs(d,a)?b[1]?0:(m(e,a),b[1]=1,dM(d[4],function(a){b[1]=0;return 0}),0):0}}else{let
a=[0,0],d=c;f=function(b){bt(b);return bs(d,b)?(i.clearTimeout(a[1]),a[1]=dM(d[3],function(a){return m(e,b)}),0):0}}cg(0,a,f,b);c=h}}}return a4(b,c)}function
d4(c,b){return ck([0,b],function(a,b){return d3(c,a,b)},"[data-request]",0)}var
cr="htmlact-request",dT="htmlact-error";function
cu(a,b){a=[0,a,b];for(;;){if(!a)return;b=a[1];a=a[2];ad(dT,1,b);ad(cr,0,b)}}function
cv(a,b){a=[0,a,b];for(;;){if(!a)return;b=a[2];ad(cr,0,a[1]);a=b}}function
d5(a,b,c){ad("htmlact-out-parent",c,a);for(;;){if(!b)return;a=b[2];ad("htmlact-out",c,b[1]);b=a}}var
d$="htmlact-in";function
d6(a,b,c){ad("htmlact-in-parent",c,a);for(;;){if(!b)return 0;a=b[2];ad(d$,c,b[1]);b=a}}function
cw(c,b){var
a=cf(ce(0,d$),c),a=a?(d6(c,b,1),dN(function(a){dN(function(a){return d6(c,b,0)});return 0}),0):a;return a}var
cc=!0;function
gB(a,b){var
h=bh(a3(a));dR(new
dQ(function(a,b){b=a.length-1|0;var
c=0;if(b<0);else{var
d=0;for(;;){var
i=a[d].addedNodes,e=i.length-1|0;if(e<0);else{var
f=0;for(;;){var
g=i.item(f),c=cj(g)?[0,g,c]:c,g=f+1|0;if(e===f)break;f=g}}e=d+1|0;if(b===d)break;d=e}}return cw(h,c)}),h,{childList:cc});a.outerHTML=b}function
bu(a,b){return"header ".concat(a).concat(a$).concat(b)}var
gM=[0,0],gN=[0,0];function
d7(a,b,c,d,e){e=br(a,e);if(!e)return gN;e=e[1];c=aM.history;d=dL(aM).toString();e=ci([0,d],e);if(0!==e[0])return O(bu(a,e[1].message));e=e[1];return k(e.toString(),d)?gM:(gU(b,0,0,[0,e],c),[0,1])}function
d8(a){return k(dI(a),"nobase")?a.pathname:a.toString()}var
d9=function(a,b){a=a?[0,a[1]]:[0];a=hw(gv,a);for(;;){if(!b)return a;var
c=b[1],b=b[2];a.append(c[1],c[2])}}(0,[0,[0,"htmlact",a9],0]),ez="beforebegin",ej="afterend",ex="afterbegin",eJ="beforeend",gC=[0,"src/page/htmlact_page.ml",524,6];function
gs(a,b,c,d){a=a?a[1]:aL;b=b?b[1]:aK;c=c?c[1]:aL;d.pushState(a,b,c);return 0}function
gt(a,b,c,d){a=a?a[1]:aL;b=b?b[1]:aK;c=c?c[1]:aL;d.replaceState(a,b,c);return 0}function
gu(a){return dG(function(a){return a},a.text())}function
gD(d,b,c){a:{var
q=function(a){if(typeof
b==="number")switch(b){case
0:gB(d,c);break;case
1:d.innerHTML=c;cw(d,bq(0,d));break}else if(0===b[0]){a=b[1];d.insertAdjacentHTML(a,c);if(k(a,ez)){a=d.previousSibling();var
e=bh(a3(d))}else if(k(a,ex)){a=b2(bq(0,d));e=d}else if(k(a,eJ)){a=b2(b3(bq(0,d)));e=d}else{if(!k(a,ej))throw j([0,p,gC],1);a=d.nextSibling();e=bh(a3(d))}cw(e,[0,a,0])}else
cf(ce(0,b[1]),d);return _(0)};if(typeof
b==="number")switch(b){case
0:var
e=[0,[0,bh(a3(d)),[0,d,0]]];break a;case
1:e=[0,[0,d,bq(0,d)]];break a}e=0}if(e){e=e[1];var
h=e[2],l=e[1];d5(l,h,1);e=0;var
a=[0,l,h],o=function(a){d5(l,h,0);return _(0)};for(;;){if(!a){e=ax(dF(e),o);break}var
m=a[2],a=a[1],g=function(a,b){var
c=i.window.getComputedStyle(b)[a],c=aw(c)?aK:c;if(I(c))return 0;var
d=dX(c);return d?d[1]:(a4(b,O(a.concat(": parse error: ").concat(c))),0)},n=g("--htmlact-out-duration",a),f=g("animation-duration",a),a=g("transition-duration",a),f=f<n?n:f,a=a<f?f:a;if(e<a){e=a;a=m}else
a=m}}else
e=_(0);return ax(e,q)}var
eG="GET",gR=[0,0],gO=[0,0],gP=[0,0],gK=[0,0],gL=[0,0],gH=[0,0],gI=[0,0],gJ=[0,0],gF=[0,0],gG=[0,0];function
gQ(l,b,c,d,e,f,g,h){var
a=[0,l,g];for(;;){if(!a)break;var
m=a[1],a=a[2];ad(dT,0,m);ad(cr,1,m)}a=k(b,eG);a||=k(b,"HEAD");m="follow";if(a){c=d8(c);d=cp(d).toString();c=I(d)?c:c.concat("?").concat(d);c=dP([0,dO(0,0,0,[0,d9],0,0,[0,b],0,[0,m],0,[0,h],0,0)],c)}else{c=d8(c);a:{b:{a=d.entries();for(;;){var
n=a.next();if(bo(n))break b;n=n.value[1];if(n
instanceof
i.File)break}a=1;break a}a=0}a=a?d:cp(d);c=dP([0,dO([0,a],0,0,[0,d9],0,0,[0,b],0,[0,m],0,[0,h],0,0)],c)}ax(dG(function(a){return a},gx(c)),function(a){if(0!==a[0]){cu(l,g);return _(a)}a=a[1];var
d=a.headers;d2(l);var
c=d7("htmlact-location-push",gs,l,g,d);if(0===c[0]){c=c[1]?gP:d7("htmlact-location-replace",gt,l,g,d);if(0===c[0]){c="htmlact-location-title";var
h=br(c,d);if(h){a:{h=h[1];try{var
b=gj(h)}catch(f){b=aG(f);if(b[1]!==a1)throw j(b,0);b=[1,b[2]];break a}b=[0,b]}c=0===b[0]?b:O(bu(c,b[1].message));if(0===c[0]){c=c[1];c=k(an.title,c)?gK:[0,an.title=c]}}else
c=gL;if(0===c[0]){c="htmlact-redirect";b=br(c,d);if(b){b=b[1];b=ci([0,dL(aM).toString()],b);if(0===b[0]){b=b[1];cv(l,g);aM.location=b;b=gF}else
b=O(bu(c,b[1].message))}else
b=gG;if(0===b[0]){b="htmlact-reload";c=br(b,d);if(c){c=c[1];b=k(a9,c)?(cv(l,g),aM.location.reload(),gH):k(cD,c)?gI:O(bu(b,ep.concat(c)))}else
b=gJ;b=0===b[0]?gO:b}}else
b=c}else
b=c}else
b=c;return 0===b[0]?ax(gu(a),function(a){if(0===a[0]){a=a[1];cv(l,g);return ax(gD(e,f,a),function(a){cq("htmlact-cycle-end");return _([0,0])})}cu(l,g);return _(a)}):(cu(l,g),_(b))}).fut.then(ah(1,function(a){return a4(l,a)}));return gR}var
gS=[0,0],gE=[0,1],dS="data-request";function
cx(a){cq("htmlact-cycle-start");var
f=a.target,a=ac(dS,f);if(a){a=a[1];var
b=ca(0,dC,a),h=4153253,e=function(a){var
g=a[2],a=a[1],i=d0([0,a],f),e=ac("data-target",f);if(e){e=e[1];var
d=cs(e),c=d[2],d=dV(f,d[1]);if(d){d=d[1];if(I(c))d=[0,d];else{d=d.querySelector(c);d=aw(d)?0:[0,d]}}else
d=0;e=d?[0,d[1]]:O(a_.concat(e).concat('" no such target'))}else
e=[0,f];if(0!==e[0])return e;e=e[1];d="data-effect";c=ac(d,f);if(c){c=c[1];try{var
b=dU(c);a:if(b){c=b[2];b=b[1].trim();if(k(b,"element"))c=[0,0,c];else if(k(b,"children"))c=[0,1,c];else if(k(b,"none"))c=[0,2,c];else if(k(b,"event"))c=c?[0,[1,c[1]],c[2]]:ae(eS);else{if(!k(b,ez)&&!k(b,ex)&&!k(b,eJ)&&!k(b,ej)){c=ae("unknown effect: ".concat(b));break a}c=[0,[0,b],c]}}else
c=ae("missing effect");b=c[2];c=c[1];if(0!==b)ae("unexpected token: ".concat(b2(b)));b=[0,c]}catch(f){b=aG(f);if(b[1]!==a1)throw j(b,0);b=O("effect: ".concat(b[2].message))}if(0===b[0]);else{b=b[1];d=d.concat(a$);b=O(d.concat(b.message))}}else
b=gE;if(0!==b[0])return b;b=b[1];d=ac("data-feedback",f);d=d?dW(f,cs(d[1]),fz,0):[0,e,0];c=ac("data-referrer-policy",f);c=c?c[1]:"same-origin";return typeof
g==="number"?h<=g?O("SSE unimplemented"):O("Websockets unimplemented"):gQ(f,g[2],a,i,e,b,d,c)};if(b){b=b[1];var
c=Z([0,b+1|0],0,a),a=Z(0,[0,b],a)}else{c=a;a=aK}b=ci([0,"nobase:/"],c);a:if(0===b[0]){b=b[1];var
d=dI(b);b:if(I(a)){if(!k(d,"ws")&&!k(d,"wss"))break b;b=[0,[0,b,-764430553]];break a}if(!k(a,"sse")&&!k(a,"SSE")){a=I(a)?eG:a;b=[0,[0,b,[0,804243368,a]]];break a}b=[0,[0,b,h]]}b=0===b[0]?e(b[1]):b}else
b=gS;return a4(f,b)}d4(cx,an.documentElement);a=new
dQ(function(a,b){function
j(a){return a.getRootNode()===an?1:0}var
b=a.length-1|0;if(b>=0){var
h=0;for(;;){var
g=a[h],d=g.addedNodes,e=d.length-1|0;if(e>=0){var
i=0;for(;;){var
c=d.item(i),f=j(c),f=f?cj(c):f;if(f){f=ac(dS,c)?1:0;if(f)d3(cx,c,0);d4(cx,c)}c=i+1|0;if(e===i)break;i=c}}g=g.removedNodes;d=g.length-1|0;if(d>=0){e=0;for(;;){j(g.item(e));c=e+1|0;if(d===e)break;e=c}}d=h+1|0;if(b===h)break;h=d}}return 0});dR(a,an.documentElement,{childList:cc,subtree:cc});cg(0,"beforeunload",function(a){return ck(0,function(a,b){if(b)return b;b=cm(ct,a);return 1-k(d1(a),b)},"[".concat(bE).concat("='true']"),0)?(dH(a),a.returnValue=e):0},aM);b0(0);return}(globalThis));
